### ISSUE TITLE
Manifest not correct when `skopeo copy` decompresses zstd image layers

### ISSUE THREAD

**Issue by achernya** [containers/skopeo#2422] opened 2024-09-11 17:44 UTC
I have an oci-dir format containers that I need to convert to docker-archive format.

```
$ tree /tmp/oci
/tmp/oci
├── blobs
│   └── sha256
│       ├── 26e533e7d03cd92f64edbffec20eed0548a27e16319c24ac03aa39108cddf93a
│       ├── 60d7481dede924ba8d98c11b32bee8adce1335a384352a905d2bade402db1ac1
│       └── 6e330f4b940daeb925e826533c1d8a66f56841aa4f72da8c4916246d9b565cda
├── index.json
└── oci-layout
```

This oci-dir contains an image layer that is Zstd compressed:

```
$ file /tmp/oci/blobs/sha256/*
/tmp/oci/blobs/sha256/26e533e7d03cd92f64edbffec20eed0548a27e16319c24ac03aa39108cddf93a: JSON data
/tmp/oci/blobs/sha256/60d7481dede924ba8d98c11b32bee8adce1335a384352a905d2bade402db1ac1: JSON data
/tmp/oci/blobs/sha256/6e330f4b940daeb925e826533c1d8a66f56841aa4f72da8c4916246d9b565cda: Zstandard compressed data (v0.8+), Dictionary ID: None
```

index.json says the manifest is `60d7481dede924ba8d98c11b32bee8adce1335a384352a905d2bade402db1ac1`,

```
$ jq </tmp/oci/blobs/sha256/60d7481dede924ba8d98c11b32bee8adce1335a384352a905d2bade402db1ac1 
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:26e533e7d03cd92f64edbffec20eed0548a27e16319c24ac03aa39108cddf93a",
    "size": 286
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+zstd",
      "digest": "sha256:6e330f4b940daeb925e826533c1d8a66f56841aa4f72da8c4916246d9b565cda",
      "size": 357018028,
      "platform": {
        "architecture": "x86_64",
        "os": "linux"
      }
    }
  ]
}
```

If I then run `skopeo copy oci:/tmp/oci docker-archive:/tmp/docker-archive.tar.gz`, I get a docker-archive formatted tarball with the contents

```
$ skopeo copy oci:/tmp/oci docker-archive:/tmp/docker-archive.tar.gz
Getting image source signatures
Copying blob 6e330f4b940d done   | 
Copying config 26e533e7d0 done   | 
Writing manifest to image destination
$ tar tf /tmp/docker-archive.tar.gz 
229df8b446de8b5df0599f10bf2d668a4ac546cd3fbd6736ca51464c6f28a065.tar
26e533e7d03cd92f64edbffec20eed0548a27e16319c24ac03aa39108cddf93a.json
ff942019440fb29bc971162f936f917fff8b5359a332c30183f8bfdfaf4e5672/layer.tar
ff942019440fb29bc971162f936f917fff8b5359a332c30183f8bfdfaf4e5672/VERSION
ff942019440fb29bc971162f936f917fff8b5359a332c30183f8bfdfaf4e5672/json
manifest.json
repositories
```

Note how the tarball is no longer zstd comrpessed, and has a new sha256sum (expected, its contents changed). If we look at the manifest:

```
$ skopeo inspect docker-archive:/tmp/docker-archive.tar.gz
{
    "Digest": "sha256:d3a0c3f7b755bb2b734cf85bb2920a421c53bb71504528591ebaf93a8d1ea581",
    "RepoTags": [],
    "Created": "0001-01-01T00:00:00Z",
    "DockerVersion": "",
    "Labels": null,
    "Architecture": "x86_64",
    "Os": "linux",
    "Layers": [
        "sha256:6e330f4b940daeb925e826533c1d8a66f56841aa4f72da8c4916246d9b565cda"
    ],
    "LayersData": [
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:6e330f4b940daeb925e826533c1d8a66f56841aa4f72da8c4916246d9b565cda",
            "Size": 1629235200,
            "Annotations": null
        }
    ],
    "Env": null
}
```

We see the *original* sha256 digest is still embedded in the manifest. This will be rejected by podman/docker. I did, however, confirm the file is named correctly, with its digest:

```
$ sha256sum 229df8b446de8b5df0599f10bf2d668a4ac546cd3fbd6736ca51464c6f28a065.tar 
229df8b446de8b5df0599f10bf2d668a4ac546cd3fbd6736ca51464c6f28a065  229df8b446de8b5df0599f10bf2d668a4ac546cd3fbd6736ca51464c6f28a065.tar
```

Here's what happens if you try to load it into podman. (Similar output from docker)

```
$ podman load -i /tmp/docker-archive.tar.gz
Getting image source signatures
Copying blob 6e330f4b940d [=====================================>] 1.5GiB / 1.5GiB | 331.1 MiB/s
Error: payload does not match any of the supported image formats:
 * oci: open /tmp/docker-archive.tar.gz/index.json: not a directory
 * oci-archive: loading index: open /var/tmp/container_images_oci1597505762/index.json: no such file or directory
 * docker-archive: writing blob: storing blob to file "/var/tmp/container_images_storage3425980194/1": happened during read: Digest did not match, expected sha256:6e330f4b940daeb925e826533c1d8a66f56841aa4f72da8c4916246d9b565cda, got sha256:229df8b446de8b5df0599f10bf2d668a4ac546cd3fbd6736ca51464c6f28a065
 * dir: open /tmp/docker-archive.tar.gz/manifest.json: not a directory
```

This is with `skopeo version 1.15.2` and `podman version 5.1.2`, although I've also built `skopeo version 1.17.0-dev` (v1.16.0-36-g9ceee81a) and confirmed the same behavior is present

**Comment by mtrmac** [comment] 2024-09-11 18:47
Thanks for reaching out.

This works as expected for me, with
```console
$ skopeo --override-os linux --insecure-policy copy --dest-compress-format zstd docker://quay.io/libpod/alpine oci:t1
$ file t1/blobs/sha256/d6a9b0ba255e48a781d43e2ce052c2c54138076298d3e330769f3a7befa7ea10
t1/blobs/sha256/d6a9b0ba255e48a781d43e2ce052c2c54138076298d3e330769f3a7befa7ea10: Zstandard compressed data (v0.8+), Dictionary ID: None
$ shasum -a 256 t1/blobs/sha256/d6a9b0ba255e48a781d43e2ce052c2c54138076298d3e330769f3a7befa7ea10                         
d6a9b0ba255e48a781d43e2ce052c2c54138076298d3e330769f3a7befa7ea10  t1/blobs/sha256/d6a9b0ba255e48a781d43e2ce052c2c54138076298d3e330769f3a7befa7ea10

$ skopeo --debug --insecure-policy copy oci:t1 docker-archive:t.tar
$ (mkdir t; cd t; tar xf ../t.tar)
$ file t/5e0d8111135538b8a86ce5fc969849efce16c455fd016bb3dc53131bcedc4da5.tar         
t/5e0d8111135538b8a86ce5fc969849efce16c455fd016bb3dc53131bcedc4da5.tar: POSIX tar archive
$ shasum -a 256 t/5e0d8111135538b8a86ce5fc969849efce16c455fd016bb3dc53131bcedc4da5.tar          
5e0d8111135538b8a86ce5fc969849efce16c455fd016bb3dc53131bcedc4da5  t/5e0d8111135538b8a86ce5fc969849efce16c455fd016bb3dc53131bcedc4da5.tar

$ skopeo --debug --insecure-policy copy docker-archive:t.tar dir:t3               
$ file t3/5e0d8111135538b8a86ce5fc969849efce16c455fd016bb3dc53131bcedc4da5            
t3/5e0d8111135538b8a86ce5fc969849efce16c455fd016bb3dc53131bcedc4da5: POSIX tar archive
$ shasum -a 256 t3/5e0d8111135538b8a86ce5fc969849efce16c455fd016bb3dc53131bcedc4da5         
5e0d8111135538b8a86ce5fc969849efce16c455fd016bb3dc53131bcedc4da5  t3/5e0d8111135538b8a86ce5fc969849efce16c455fd016bb3dc53131bcedc4da5
```

FWIW, note that the layer data in `skopeo inspect` is _not_ raw contents of the actual manifest; it’s a synthetic v2s2 manifest to allow consuming the archive, and in particular the digests are supposed to be a decompressed version of the layer. 

Can you provide the original image, or _complete_ steps to reproduce?

---

As an educated guess, it seems that the original OCI image’s config contains a compressed digest in `RootFs.DiffIDs`; that’s invalid, and it propagates into the `docker-archive` synthetic manifest. 

Notably the layer _size_ for 6e330f4b940daeb925e826533c1d8a66f56841aa4f72da8c4916246d9b565cda changes between `oci` and `docker-archive`.

**Comment by achernya** [comment] 2024-09-11 20:24
> Can you provide the original image, or complete steps to reproduce?

Unfortunately the original image came out of https://github.com/facebookincubator/antlir/blob/main/antlir/antlir2/antlir2_packager/src/oci.rs and I don't have a particularly good way to run it standalone at the moment.

> the original OCI image’s config contains a compressed digest in RootFs.DiffIDs; that’s invalid, and it propagates into the docker-archive synthetic manifest

As in, you're saying

```
      "digest": "sha256:6e330f4b940daeb925e826533c1d8a66f56841aa4f72da8c4916246d9b565cda",
```

from the manifest is incorrect, because it's the digest of the .tar.zst, rather than the .tar pre-zstd? If so, that's consistent with what https://github.com/opencontainers/image-spec/blob/main/config.md#layer-diffid says DiffId should be -- and indicates oci.rs did the wrong thing. 

```
$ sha256sum blobs/sha256/*
26e533e7d03cd92f64edbffec20eed0548a27e16319c24ac03aa39108cddf93a  blobs/sha256/26e533e7d03cd92f64edbffec20eed0548a27e16319c24ac03aa39108cddf93a
60d7481dede924ba8d98c11b32bee8adce1335a384352a905d2bade402db1ac1  blobs/sha256/60d7481dede924ba8d98c11b32bee8adce1335a384352a905d2bade402db1ac1
6e330f4b940daeb925e826533c1d8a66f56841aa4f72da8c4916246d9b565cda  blobs/sha256/6e330f4b940daeb925e826533c1d8a66f56841aa4f72da8c4916246d9b565cda
```

As you predicted, the oci.rs encodes the compressed bytes:

https://github.com/facebookincubator/antlir/blob/main/antlir/antlir2/antlir2_packager/src/oci.rs#L139-L140 and then used in https://github.com/facebookincubator/antlir/blob/main/antlir/antlir2/antlir2_packager/src/oci.rs#L155

I've hacked on this locally (it'll get fixed in github after I get it reviewed) and

```
$ skopeo copy oci:/tmp/oci docker-archive:/tmp/docker-archive.tar.gz
Getting image source signatures
Copying blob 6e330f4b940d done   | 
Copying config 3f8fbd7367 done   | 
Writing manifest to image destination
$ podman load -i /tmp/docker-archive.tar.gz
Getting image source signatures
Copying blob 229df8b446de done   | 
Copying config 3f8fbd7367 done   | 
Writing manifest to image destination
Loaded image: sha256:3f8fbd7367bd162d8e15711a74fcd6c9b2dfe8990898e2b6ef3157e3ea025609
```

Thanks for your help, and sorry for the false alarm!

**Comment by mtrmac** [comment] 2024-09-18 21:02
Thanks! Per the linked https://github.com/facebookincubator/antlir/commit/9968b474910e73efd406ddfe0b6d1e22b6fb717e , I understand that this has been fixed on the producer side.

Please reopen if there are any outstanding problems.

**Closed by mtrmac** 2024-09-18 21:02 UTC

**Comment by cgwalters** [comment] 2024-09-18 22:29
> Thanks! Per the linked facebookincubator/antlir@9968b47 , I understand that this has been fixed on the producer side.

You may also want to take a look at using https://github.com/containers/ocidir-rs/ which is both correct and pretty widely tested now as it's used by https://github.com/ostreedev/ostree-rs-ext as well as https://github.com/microsoft/rpmoci/ nowadays.

Which, when I glance at your code, it looks like we should add zstd support there, but that's relatively straightforward.

**Comment by achernya** [comment] 2024-09-19 16:47
@cgwalters Thanks for the tip! Will take a look.
