### ISSUE TITLE
Get remote image size

### ISSUE THREAD

**Issue by harik8** [containers/skopeo#936] opened 2020-06-01 08:35 UTC
In Skopeo inspect I couldn't find image size.

How to get the size of an image using Skopeo?

**Comment by TomSweeneyRedHat** [comment] 2020-06-01 14:30
If @mtrmac says differently, trust his answer over mine.  There's currently not a way to get the image size via Skopeo..  It's something that's been discussed prior and we've another issue for it that's still open, #641.   I think it would be a good thing to have in the inspect output, but I don't believe it's a quick fix as you'd expect. 

As this is a duplicate of #641, I'm going to close this and the discussion can continue there.

**Closed by TomSweeneyRedHat** 2020-06-01 14:30 UTC

**Comment by mtrmac** [comment] 2020-06-01 14:59
Yeah; it’s not currently available. It can’t be computed for schema1 without pulling the image, but it is possible for schema2/OCI, and it would make sense to provide it.
