### ISSUE TITLE
skopeo login may need write permissions to /run/containers

### ISSUE THREAD

**Issue by jonstelly** [containers/skopeo#1240] opened 2021-04-09 20:44 UTC
I'm trying to run Skopeo on Ubuntu 20.04 in WSL2.  I followed [this guide](https://www.answertopia.com/ubuntu/working-with-containers-on-ubuntu/) for installing.  `skopeo version 1.2.2`

## Initial Issue - docker:// prefix in README.md
Following the instructions from the skopeo README.md at the root of this repository I couldn't connect to any docker registries.  I have a private registry and an azure acr registry.  Both fail with the same error

```
> az acr credential show -n <my-acr>
{
  "passwords": [
    {
      "name": "password",
      "value": "..."
    },
    {
      "name": "password2",
      "value": "..."
    }
  ],
  "username": "<my-acr>"
}
> skopeo login docker://<my-acr>.azurecr.io --username <my-acr>
Password: ...
FATA[0033] error authenticating creds for "docker:": error pinging docker registry docker:: Get "https://docker/v2/": dial tcp: lookup docker on 172.20.208.1:53: no such host
```

I tried running this in an ubuntu docker image (using the 20.10/rolling image) and got a similar result:

```
> docker run -it --rm ubuntu:rolling
> apt update && apt install skopeo
> skopeo login --username <my-arc> docker://<my-arc>.azurecr.io
Password:
FATA[0028] error authenticating creds for "docker:": error pinging docker registry docker:: Get "https://docker/v2/": dial tcp: lookup docker on 192.168.65.5:53: read udp 172.17.0.5:59199->192.168.65.5:53: i/o timeout
```

I then noticed that the [login docs](https://github.com/containers/skopeo/blob/master/docs/skopeo-login.1.md) show a different format than what's in the [README.md at the root of this repository](https://github.com/containers/skopeo/blob/master/README.md) (no `docker://` prefix), so maybe this is just a documentation error?

## Next Issue - /run/containers missing in WSL?
If I omit the `docker://` scheme/prefix then I now get a different error: `FATA[0001] mkdir /run/containers: permission denied`.  So if I run with `sudo skopeo login ...` it works, same with `skopeo copy ...` but I'm a bit confused because the skopeo README says `skopeo does not require the user to be running as root to do most of its operations.`

Is there something I'm doing wrong or missing?  It would be nice to not have to runt his as root, trying to test it out for my CI/CD build agents.

**Comment by vrothberg** [comment] 2021-04-12 09:29
Regarding the login error:
> dial tcp: lookup docker on 172.20.208.1:53: no such host

This looks outside the doings of Skopeo.  Is something funky going on with the hosts DNS?

Regarding Skopeo in a container:
It depends on the version of Skopeo. It looks like Skopeo thinks it's running as root (maybe related to the Docker env).  You can explicitly overwrite the path of the auth file by using the `REGISTRY_AUTH_FILE` environment variable.  The official Skopeo image at `quay.io/containers/skopeo` sets `REGISTRY_AUTH_FILE=/auth.json`.

**Comment by jonstelly** [comment] 2021-04-12 19:01
I read that not as a problem connecting to DNS, but that skopeo is trying to resolve the hostname `docker` via DNS and that's not the host I'm trying to connect to.  My hub DNS name is `hub.my.domain`.

It seems like the `docker://` scheme isn't supported or required for the login command.  I just submitted a PR to fix the root README.md to remove that guidance.

Here's some debug output in case it sheds more light:
```log
> skopeo login docker://hub.my.domain --username me --debug
DEBU[0000] Credentials not found
Password:
DEBU[0010] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker:
DEBU[0010] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0010] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf"
DEBU[0010] GET https://docker:/v2/
DEBU[0012] Ping https://docker:/v2/ err Get "https://docker/v2/": dial tcp: lookup docker on 172.27.112.1:53: no such host (&url.Error{Op:"Get", URL:"https://docker/v2/", Err:(*net.OpError)(0xc00071c6e0)})
DEBU[0012] GET https://docker:/v1/_ping
DEBU[0014] Ping https://docker:/v1/_ping err Get "https://docker/v1/_ping": dial tcp: lookup docker on 172.27.112.1:53: no such host (&url.Error{Op:"Get", URL:"https://docker/v1/_ping", Err:(*net.OpError)(0xc0000a6190)})
FATA[0014] error authenticating creds for "docker:": error pinging docker registry docker:: Get "https://docker/v2/": dial tcp: lookup docker on 172.27.112.1:53: no such host
```

And setting the REGISTRY_AUTH_FILE environment variable to a path under my home directory fixes the sudo issue so thanks for that.

It does raise a question, I'm trying to run skopeo outside of docker (simple binary installed in my WSL instance).  I'm not running the command as root so it seems odd that skopeo would default to trying to use the auth file under `/run/containers`.  Shouldn't skopeo try to use an auth file like `$HOME/.skopeo/auth.json` or something as a default since not having to run docker or run as root is one of the major benefits of skopeo?

**Comment by vrothberg** [comment] 2021-04-13 07:34
> It seems like the docker:// scheme isn't supported or required for the login command. I just submitted a PR to fix the root README.md to remove that guidance.

You're absolutely right. Thank you for fixing the README :+1:

**Comment by vrothberg** [comment] 2021-04-13 07:39
> It does raise a question, I'm trying to run skopeo outside of docker (simple binary installed in my WSL instance). I'm not running the command as root so it seems odd that skopeo would default to trying to use the auth file under /run/containers. Shouldn't skopeo try to use an auth file like $HOME/.skopeo/auth.json or something as a default since not having to run docker or run as root is one of the major benefits of skopeo?

Yes, that is usually the case. In case of an ordinary rootless user, Skopeo (and other tools based on the github.com/containers/image library) will use `/run/user/$UID/containers/auth.json`.

I do not have access to a Windows machine to try and test on WSL but it is something we should investigate.  I suggest to leave the issue open until we can shed some light on it.

**Comment by jonstelly** [comment] 2021-04-13 08:12
Ah, on WSL2 the `/run/user/$UID` directory doesn't exist.  After I created that directory as root and chmod+chown I was able to unset the REGISTRY_AUTH_FILE environment variable and everything worked rootless.

It might be nice to document the couple options for WSL folks (assuming others will run into this).  Either:

1. Setting the REGISTRY_AUTH_FILE environment variable in your profile to a user-writable location - requires no root commands
2. A one-time root procedure of:

```bash
sudo mkdir /run/user/1000
chown 1000 /run/user/1000
chmod 700 /run/user/1000
```

Thanks for the help!

**Comment by cevich** [comment] 2021-06-08 17:26
I'm seeing this / similar problem under Github Actions on Ubuntu 20.04.  I [confirmed in their build-scripts](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/containers.sh), they're installing skopeo from `https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable`:

```
time="2021-06-03T14:53:07Z" level=fatal msg="error reading auth file: 1 error occurred:\n\t* error reading JSON file \"/run/containers/1001/auth.json\": open /run/containers/1001/auth.json: permission denied\n\n"
```

I looked and found `/run/containers` is root:root and 0550 (IIRC).  Could something be wrong on the packaging side @lsm5 ?

**Comment by lsm5** [comment] 2021-07-06 19:40
@cevich it doesn't look like packaging provides any auth.json file anywhere, so I'm not sure there's anything to fix here apart from any documentation. Correct me if I'm wrong.

**Comment by mtrmac** [comment] 2021-07-07 21:14
> ```
> time="2021-06-03T14:53:07Z" level=fatal msg="error reading auth file: 1 error occurred:\n\t* error reading JSON file \"/run/containers/1001/auth.json\": open /run/containers/1001/auth.json: permission denied\n\n"
> ```
> 
> I looked and found `/run/containers` is root:root and 0550 (IIRC). Could something be wrong on the packaging side @lsm5 ?

(@cevich @lsm5 Just a drive-by without reading the full context I’m afraid, to prevent making things worse:) It is basically known/expected that non-root accesses without systemd or the like fail, and that does seem to include most containers as non-root. The intent was for `auth.json` to be written to RAM/tmpfs only, and such user-writable locations only (safely) exist if something creates them. Various aspects of this are problematic, and could be discussed at length or revisited, and this might well be the right place and right reason for it — right now I only want to say that making `/run/containers` world-writable in our packaging would _not_ be desirable; that would be at best as secure as using `/tmp` instead of `/run/containers`, and that was, at the time, intentionally not done.

The happy path is to set `XDG_RUNTIME_DIR`, ideally by the login mechanism without users knowing. `REGISTRY_AUTH_FILE` is probably the next best thing right now.

**Comment by cevich** [comment] 2021-07-12 15:36
I understand what you're saying @mtrmac and I agree in principal.  IIRC, my fear is mostly around the user experience and consistency with podman and buildah.  I know we don't create the auth file @lsm5,  I was questioning if maybe this environment was picking up an outdated skopeo package with a fix you were aware of.  It sounds like not, and this could easily be caused by some github-actions specific environment goofiness.  I will manually confirm using some fresh VMs and the Kubik packages also used by github actions.

**Comment by cevich** [comment] 2021-07-12 17:48
Confirmed: Skopeo 1.3.0 from Kubik (and elsewhere?) is behaving differently from podman (3.2.2) and buildah (1.21.1) on the same VM (Ubuntu 20.10):

```
root@cevich-prior-ubuntu-c6248193773010944:~# adduser foo
Adding user `foo' ...cut...
Is the information correct? [Y/n] y
root@cevich-prior-ubuntu-c6248193773010944:~# su - foo
foo@cevich-prior-ubuntu-c6248193773010944:~$ podman login -u testuser -p testpassword --cert-dir /tmp/auth localhost:5000
Login Succeeded!

foo@cevich-prior-ubuntu-c6248193773010944:~$ buildah login -u testuser -p testpassword -
-cert-dir /tmp/auth localhost:5000
Login Succeeded!

foo@cevich-prior-ubuntu-c6248193773010944:~$ skopeo login -u testuser -p testpassword --
cert-dir /tmp/auth localhost:5000
FATA[0000] reading auth file: 1 error occurred:
        * error reading JSON file "/run/containers/1000/auth.json": open /run/containers/1000/auth.json: permission denied

foo@cevich-prior-ubuntu-c6248193773010944:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy

foo@cevich-prior-ubuntu-c6248193773010944:~$ echo $REGISTRY_AUTH_FILE

foo@cevich-prior-ubuntu-c6248193773010944:~$ echo $XDG_RUNTIME_DIR
```

Then I tried connecting with ssh as the user `foo` (instead of using `su`).  Now everything works fine (including skopeo)!  I also noticed:

```
foo@cevich-prior-ubuntu-c6248193773010944:~$ echo $XDG_RUNTIME_DIR
/run/user/1000
```

So this makes sense, github actions must be providing a non-login shell (similar to `su`) and therefore the user environment isn't being completely setup.  However, **somehow** both podman and buildah seem to navigate this issue successfully whereas skopeo does not.  So I did some poking around with `podman login...`  in debug mode and found this:

```
foo@cevich-prior-ubuntu-c6248193773010944:~# su - foo
foo@cevich-prior-ubuntu-c6248193773010944:~$ podman --log-level debug login -u testuser -p testpassword --cert-dir /tmp/auth localhost:5000
...cut...
DEBU[0000] No credentials for localhost:5000 found
DEBU[0000] GET https://localhost:5000/v2/
DEBU[0000] Ping https://localhost:5000/v2/ status 401
DEBU[0000] GET https://localhost:5000/v2/
DEBU[0000] Stored credentials for localhost:5000 in credential helper containers-auth.json
Login Succeeded!
...cut...
foo@cevich-prior-ubuntu-c6248193773010944:~$ find /tmp -type f -name '*auth.json'
/tmp/podman-run-1000/containers/auth.json
...cut bunch of permission-denied results...
```

This must be a fallback for when no `/run/user/<ID>` exists, and neither `$XDG_RUNTIME_DIR` nor `$REGISTRY_AUTH_FILE` are set.  Can we confirm this with the podman/buildah folks?  Then consider making Skopeo behave the same (as all users likely expect)?

**Comment by mtrmac** [comment] 2021-07-12 18:37
IIRC Podman has, for most of its existence, found it worthwhile to set or override `XDG_RUNTIME_DIR` inside the process; the current iteration seems to be https://github.com/containers/podman/blob/4458d2230e31c963e740a78878d593cfe6e2f0a5/libpod/runtime.go#L132 . That makes it pretty hard for a third-party to sustainably coordinate with Podman (even if a third party _wanted_ to do exactly what Podman does, which is already a stretch, the fallback path has IIRC changed at least once). Skopeo isn’t quite a third party, and could share the logic maybe in c/common , but it’s difficult for me to feel too enthusiastic about that — and anyway it doesn’t work for non-Skopeo users of c/image: a library like c/image just must not dare to change a process-wide environment variable with such a wide reach as `XDG_RUNTIME_DIR`.

(And even if we did get rid of the `XDG_RUNTIME_DIR` value discrepancy, the ultimate fallback of `/run/containers/$uid` would _still_ be unusable by non-root third-party users of c/image. OTOH that AFAICS just doesn’t have a solution given the currently valued constraints. A possible avenue would be to give up on the whole “`auth.json` is not supposed to exist on disk” idea, or alternatively to make it irrelevant, maybe by somehow ensuring there is always some other credential helper (which seems ~impossible, if we can’t rely on the environment to have a tmpfs mount, we absolutely can’t rely on it to have a secret storage API), or to declare non-systemd environments unsupported (similarly ~impossible).)

**Comment by cevich** [comment] 2021-07-12 19:10
> A possible avenue would be to give up on the whole “auth.json is not supposed to exist on disk” idea

[See my comment over in Ed's issue](https://github.com/containers/skopeo/issues/823#issuecomment-878520837), I think this is the right approach.  Fallback to `/tmp/skopeo-run-1000/containers/auth.json` and call that good enough - there really are very few other options as you've also concluded.

In any case, I'm going to close this issue in favor of #823 before we go crazy.  They seem to be the same problem, and Ed opened his first :grin:

**Closed by cevich** 2021-07-12 19:10 UTC
Labels: packaging
