### ISSUE TITLE
RFE: skopeo should check if the image already exists in the destination registry

### ISSUE THREAD

**Issue by opuk** [containers/skopeo#395] opened 2017-08-10 13:59 UTC
skopeo copy docker://$SRC_REG/$img:$tag docker://$DEST_REG/$img:$tag

Currently skopeo will copy the image again if the image already exists in the destination registry. It would be nice if a check was done with the copy command so it would not copy images that already exists.
If such a check is implemented it should probably be possible to override it however.

**Comment by mtrmac** [comment] 2017-08-28 19:42
Thanks for the report.

This is non-trivial in the general case (see #281 for a more specific variant of this suggestion), but probably reasonably easily possible for the simple cases.

**Comment by ameade** [comment] 2017-10-23 15:56
Hey,

 I have also noticed that all image layers are copied to the destination registry even if they already exist there. This is a big problem when copying images all over the world. Is there an estimate on when this will be implemented? Is this what this issue is about?

**Comment by mtrmac** [comment] 2017-10-23 16:04
> I have also noticed that all image layers are copied to the destination registry even if they already exist there

Noticed how?  What are the exact steps of reproduce? Ordinarily pre-existing layers should not be redundantly copied, at least as long as the destination can tell the client that the layer is already present.

This issue seems more focused on the overhead of copying configs & manifests, and the overhead necessary to even avoid determining that the layers are already present.

**Comment by myllynen** [comment] 2017-10-24 05:56
```
[root@localhost ~]# skopeo --version
skopeo version 0.1.23 commit: 24510500d48f15b52ddfed6972a2a56452ef16b6
[root@localhost ~]# skopeo copy docker://registry.access.redhat.com/rhel7/etcd:latest docker://registry.example.com:5000/rhel7/etcd:latest
Getting image source signatures
Copying blob sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9
 71.39 MB / ? [------------------------=--------------------------------------] 
Copying blob sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d
 1.21 KB / ? [------------------------------------------------------------=---] 
Copying blob sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab
 14.31 MB / ? [--------=------------------------------------------------------] 
Copying config sha256:797a818d8f9e3393b8c44cde94bc2108530afa4adb119d81166e7a69dbd4ad1e
 7.67 KB / 7.67 KB [===========================================================]
Writing manifest to image destination
Storing signatures
[root@localhost ~]# skopeo copy docker://registry.access.redhat.com/rhel7/etcd:latest docker://registry.example.com:5000/rhel7/etcd:latest
Getting image source signatures
Copying blob sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9
 71.34 MB / ? [---------------------------------------------------------------=]
Copying blob sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d
 0 B / ? [--------------------------------------------------------------------=]
Copying blob sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab
 14.25 MB / ? [---------------------------------------------------------------=]
Copying config sha256:797a818d8f9e3393b8c44cde94bc2108530afa4adb119d81166e7a69dbd4ad1e
 0 B / 7.67 KB [---------------------------------------------------------------]
Writing manifest to image destination
Storing signatures
[root@localhost ~]# 
```

It would certainly be desirable to have this working with this type destination. Thanks.

**Comment by mtrmac** [comment] 2017-10-24 16:16
@myllynen That seems unexpected. Can you file a separate issue for this non-working deduplication, and in there, provide the output of the two commands with `skopeo --debug copy …`, please?

**Comment by myllynen** [comment] 2017-10-25 07:35
@mtrmac This issues was filed exactly about what was demonstrated above so I'm not sure do we need another issue?

In any case, here's the debug output, now from Fedora 27 Beta / skopeo-1.24:

```
[root@localhost ~]# skopeo --version
skopeo version 0.1.24 commit: b9e887956fa3027fd06a467575b6e160c469d2e7
[root@localhost ~]# skopeo --debug copy docker://registry.access.redhat.com/rhel7/etcd:latest docker://registry.example.com:5000/rhel7/etcd:latest
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]   Using file:///var/lib/atomic/sigstore      
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/registry.example.com:5000 
DEBU[0000]  crt: /etc/docker/certs.d/registry.example.com:5000/cert.crt 
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for registry.access.redhat.com/rhel7/etcd:latest 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/registry.access.redhat.com 
DEBU[0000] IsRunningImageAllowed for image docker:registry.access.redhat.com/rhel7/etcd:latest 
DEBU[0000]  Using default policy section                
DEBU[0000]  Requirement 0: allowed                      
DEBU[0000] Overall: allowed                             
DEBU[0000] GET https://registry.access.redhat.com/v2/   
DEBU[0001] Ping https://registry.access.redhat.com/v2/ err <nil> 
DEBU[0001] Ping https://registry.access.redhat.com/v2/ status 200 
DEBU[0001] GET https://registry.access.redhat.com/v2/rhel7/etcd/manifests/latest 
Getting image source signatures
DEBU[0003] Manifest has MIME type text/plain, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0003] Checking /v2/rhel7/etcd/blobs/sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0003] GET https://registry.example.com:5000/v2/    
DEBU[0003] Ping https://registry.example.com:5000/v2/ err <nil> 
DEBU[0003] Ping https://registry.example.com:5000/v2/ status 200 
DEBU[0003] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0003] ... not present                              
Copying blob sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9
DEBU[0003] Downloading /v2/rhel7/etcd/blobs/sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0003] GET https://registry.access.redhat.com/v2/rhel7/etcd/blobs/sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0005] Detected compression format gzip             
 0 B / ? [--------------------------------------------------------------------=]DEBU[0005] Using original blob without modification     
DEBU[0005] Checking /v2/rhel7/etcd/blobs/sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0005] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0005] ... not present                              
DEBU[0005] Uploading /v2/rhel7/etcd/blobs/uploads/      
DEBU[0005] POST https://registry.example.com:5000/v2/rhel7/etcd/blobs/uploads/ 
DEBU[0005] PATCH https://registry.example.com:5000/v2/rhel7/etcd/blobs/uploads/bb02ec0d-13ae-45cf-a452-410a5c4aa10b?_state=pHhejVDBbNeDFvSPSpHL5pJsGWfvV3_N_g2gcib5nsl7Ik5hbWUiOiJyaGVsNy9ldGNkIiwiVVVJRCI6ImJiMDJlYzBkLTEzYWUtNDVjZi1hNDUyLTQxMGE1YzRhYTEwYiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNy0xMC0yNVQwNzoxMjowOS40ODY0OTM0MzJaIn0%3D 
 71.39 MB / ? [------------------------=--------------------------------------] DEBU[0059] PUT https://registry.example.com:5000/v2/rhel7/etcd/blobs/uploads/bb02ec0d-13ae-45cf-a452-410a5c4aa10b?_state=AWxCPmuhNym9xUUxCivKoWcpTnCF_nEmyKZurtDfWB97Ik5hbWUiOiJyaGVsNy9ldGNkIiwiVVVJRCI6ImJiMDJlYzBkLTEzYWUtNDVjZi1hNDUyLTQxMGE1YzRhYTEwYiIsIk9mZnNldCI6NzQ4NTc3MDMsIlN0YXJ0ZWRBdCI6IjIwMTctMTAtMjVUMDc6MTI6MDlaIn0%3D&digest=sha256%3A76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0059] Upload of layer sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 complete 
DEBU[0059] Consuming rest of the original blob to satisfy getOriginalLayerCopyWriter 
 71.39 MB / ? [------------------------------------=----------------------] 54s 
DEBU[0059] Computed DiffID sha256:f4c74f205954fed1127474d1d58614639a0d560fe3bab9c9c1abd51ad7426fe7 for layer sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0059] Checking /v2/rhel7/etcd/blobs/sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0059] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0060] ... not present                              
Copying blob sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d
DEBU[0060] Downloading /v2/rhel7/etcd/blobs/sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0060] GET https://registry.access.redhat.com/v2/rhel7/etcd/blobs/sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0062] Detected compression format gzip             
 0 B / ? [--------------------------------------------------------------------=]DEBU[0062] Using original blob without modification     
DEBU[0062] Checking /v2/rhel7/etcd/blobs/sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0062] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0062] ... not present                              
DEBU[0062] Uploading /v2/rhel7/etcd/blobs/uploads/      
DEBU[0062] POST https://registry.example.com:5000/v2/rhel7/etcd/blobs/uploads/ 
DEBU[0062] PATCH https://registry.example.com:5000/v2/rhel7/etcd/blobs/uploads/8999ab13-9890-430a-a6c8-dba9d82c5bef?_state=jbmMarwGBj6zIFntD0a2p-2VMqeVlLvFY3YnxRjnI5F7Ik5hbWUiOiJyaGVsNy9ldGNkIiwiVVVJRCI6Ijg5OTlhYjEzLTk4OTAtNDMwYS1hNmM4LWRiYTlkODJjNWJlZiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNy0xMC0yNVQwNzoxMzowNi4yMDMzMDU3OThaIn0%3D 
DEBU[0062] PUT https://registry.example.com:5000/v2/rhel7/etcd/blobs/uploads/8999ab13-9890-430a-a6c8-dba9d82c5bef?_state=gWVdgIjYYYVcKsALjY4H6_6FFdPCq23P_lJf6Semx0J7Ik5hbWUiOiJyaGVsNy9ldGNkIiwiVVVJRCI6Ijg5OTlhYjEzLTk4OTAtNDMwYS1hNmM4LWRiYTlkODJjNWJlZiIsIk9mZnNldCI6MTIzOSwiU3RhcnRlZEF0IjoiMjAxNy0xMC0yNVQwNzoxMzowNloifQ%3D%3D&digest=sha256%3A26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
 1.21 KB / ? [------------------------------------------------------------=---] DEBU[0062] Upload of layer sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d complete 
DEBU[0062] Consuming rest of the original blob to satisfy getOriginalLayerCopyWriter 
 1.21 KB / ? [=------------------------------------------------------------] 0s 
DEBU[0062] Computed DiffID sha256:6430b71902c3cba4695af52c9fedfff62fc8c90f2705204c248783f4c6e4ca5c for layer sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0062] Checking /v2/rhel7/etcd/blobs/sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0062] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0062] ... not present                              
Copying blob sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab
DEBU[0062] Downloading /v2/rhel7/etcd/blobs/sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0062] GET https://registry.access.redhat.com/v2/rhel7/etcd/blobs/sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0064] Detected compression format gzip             
 0 B / ? [--------------------------------------------------------------------=]DEBU[0064] Using original blob without modification     
DEBU[0064] Checking /v2/rhel7/etcd/blobs/sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0064] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0064] ... not present                              
DEBU[0064] Uploading /v2/rhel7/etcd/blobs/uploads/      
DEBU[0064] POST https://registry.example.com:5000/v2/rhel7/etcd/blobs/uploads/ 
DEBU[0064] PATCH https://registry.example.com:5000/v2/rhel7/etcd/blobs/uploads/19d55557-0bb7-4e51-b074-beda9bd165a1?_state=gmr-N2y0ytXZb8u1FNZI_VCXBVKePw-zfPqRS5hC_id7Ik5hbWUiOiJyaGVsNy9ldGNkIiwiVVVJRCI6IjE5ZDU1NTU3LTBiYjctNGU1MS1iMDc0LWJlZGE5YmQxNjVhMSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNy0xMC0yNVQwNzoxMzowOC4zMjM5ODI0NDZaIn0%3D 
 14.31 MB / ? [--------=------------------------------------------------------] DEBU[0075] PUT https://registry.example.com:5000/v2/rhel7/etcd/blobs/uploads/19d55557-0bb7-4e51-b074-beda9bd165a1?_state=mtns4n5J8CGtCEhYX0e5RAD9oK0rsvwcBQSS-rPa8L57Ik5hbWUiOiJyaGVsNy9ldGNkIiwiVVVJRCI6IjE5ZDU1NTU3LTBiYjctNGU1MS1iMDc0LWJlZGE5YmQxNjVhMSIsIk9mZnNldCI6MTUwMDUyMzksIlN0YXJ0ZWRBdCI6IjIwMTctMTAtMjVUMDc6MTM6MDhaIn0%3D&digest=sha256%3Ad2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0075] Upload of layer sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab complete 
DEBU[0075] Consuming rest of the original blob to satisfy getOriginalLayerCopyWriter 
 14.31 MB / ? [----------------------------------------=------------------] 10s 
DEBU[0075] Computed DiffID sha256:acff9253c91e74690aa64d0abbceff06fafb4140acdfe0fceb4c7006fd0e7428 for layer sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
Copying config sha256:797a818d8f9e3393b8c44cde94bc2108530afa4adb119d81166e7a69dbd4ad1e
DEBU[0075] No compression detected                      
 0 B / 7.67 KB [---------------------------------------------------------------]DEBU[0075] Using original blob without modification     
DEBU[0075] Checking /v2/rhel7/etcd/blobs/sha256:797a818d8f9e3393b8c44cde94bc2108530afa4adb119d81166e7a69dbd4ad1e 
DEBU[0075] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:797a818d8f9e3393b8c44cde94bc2108530afa4adb119d81166e7a69dbd4ad1e 
DEBU[0075] ... not present                              
DEBU[0075] Uploading /v2/rhel7/etcd/blobs/uploads/      
DEBU[0075] POST https://registry.example.com:5000/v2/rhel7/etcd/blobs/uploads/ 
DEBU[0075] PATCH https://registry.example.com:5000/v2/rhel7/etcd/blobs/uploads/393397d6-717f-4c0a-92ea-1e304d82d27c?_state=Tjnnw04eHUCPh69JYdVG_XmO7arrsQUGVmEP33xjK-t7Ik5hbWUiOiJyaGVsNy9ldGNkIiwiVVVJRCI6IjM5MzM5N2Q2LTcxN2YtNGMwYS05MmVhLTFlMzA0ZDgyZDI3YyIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNy0xMC0yNVQwNzoxMzoxOS4xMTUwNDAyMjRaIn0%3D 
 7.67 KB / 7.67 KB [===========================================================]DEBU[0075] PUT https://registry.example.com:5000/v2/rhel7/etcd/blobs/uploads/393397d6-717f-4c0a-92ea-1e304d82d27c?_state=AqpC9mAxPEusPGDvxI0ZU-ngH7Vk-RUwLzLbEPnDBCZ7Ik5hbWUiOiJyaGVsNy9ldGNkIiwiVVVJRCI6IjM5MzM5N2Q2LTcxN2YtNGMwYS05MmVhLTFlMzA0ZDgyZDI3YyIsIk9mZnNldCI6Nzg1NSwiU3RhcnRlZEF0IjoiMjAxNy0xMC0yNVQwNzoxMzoxOVoifQ%3D%3D&digest=sha256%3A797a818d8f9e3393b8c44cde94bc2108530afa4adb119d81166e7a69dbd4ad1e 
DEBU[0075] Upload of layer sha256:797a818d8f9e3393b8c44cde94bc2108530afa4adb119d81166e7a69dbd4ad1e complete 
 7.67 KB / 7.67 KB [========================================================] 0s
Writing manifest to image destination
DEBU[0075] PUT https://registry.example.com:5000/v2/rhel7/etcd/manifests/latest 
Storing signatures
[root@localhost ~]# skopeo --debug copy docker://registry.access.redhat.com/rhel7/etcd:latest docker://registry.example.com:5000/rhel7/etcd:latest
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]   Using file:///var/lib/atomic/sigstore      
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/registry.example.com:5000 
DEBU[0000]  crt: /etc/docker/certs.d/registry.example.com:5000/cert.crt 
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for registry.access.redhat.com/rhel7/etcd:latest 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/registry.access.redhat.com 
DEBU[0000] IsRunningImageAllowed for image docker:registry.access.redhat.com/rhel7/etcd:latest 
DEBU[0000]  Using default policy section                
DEBU[0000]  Requirement 0: allowed                      
DEBU[0000] Overall: allowed                             
DEBU[0000] GET https://registry.access.redhat.com/v2/   
DEBU[0001] Ping https://registry.access.redhat.com/v2/ err <nil> 
DEBU[0001] Ping https://registry.access.redhat.com/v2/ status 200 
DEBU[0001] GET https://registry.access.redhat.com/v2/rhel7/etcd/manifests/latest 
Getting image source signatures
DEBU[0002] Manifest has MIME type text/plain, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0002] Checking /v2/rhel7/etcd/blobs/sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0002] GET https://registry.example.com:5000/v2/    
DEBU[0002] Ping https://registry.example.com:5000/v2/ err <nil> 
DEBU[0002] Ping https://registry.example.com:5000/v2/ status 200 
DEBU[0002] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0002] ... already exists                           
Copying blob sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9
DEBU[0002] Downloading /v2/rhel7/etcd/blobs/sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0002] GET https://registry.access.redhat.com/v2/rhel7/etcd/blobs/sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0004] Detected compression format gzip             
 0 B / ? [--------------------------------------------------------------------=]DEBU[0004] Using original blob without modification     
DEBU[0004] Checking /v2/rhel7/etcd/blobs/sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0004] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0004] ... already exists                           
DEBU[0004] Consuming rest of the original blob to satisfy getOriginalLayerCopyWriter 
 71.39 MB / ? [------------------------------------------------------=--] 1m18s 
DEBU[0083] Computed DiffID sha256:f4c74f205954fed1127474d1d58614639a0d560fe3bab9c9c1abd51ad7426fe7 for layer sha256:76b0264c130a031b05e695bf175147575b93271c9c838408ba63daaa7de934e9 
DEBU[0083] Checking /v2/rhel7/etcd/blobs/sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0083] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0083] ... already exists                           
Copying blob sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d
DEBU[0083] Downloading /v2/rhel7/etcd/blobs/sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0083] GET https://registry.access.redhat.com/v2/rhel7/etcd/blobs/sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0085] Detected compression format gzip             
 0 B / ? [--------------------------------------------------------------------=]DEBU[0085] Using original blob without modification     
DEBU[0085] Checking /v2/rhel7/etcd/blobs/sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0085] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0085] ... already exists                           
DEBU[0085] Consuming rest of the original blob to satisfy getOriginalLayerCopyWriter 
 1.21 KB / ? [=------------------------------------------------------------] 0s 
DEBU[0085] Computed DiffID sha256:6430b71902c3cba4695af52c9fedfff62fc8c90f2705204c248783f4c6e4ca5c for layer sha256:26dc84c55415d3296f5faef853d2ff7a5da199b6fd26ba0f942da7285ee7e88d 
DEBU[0085] Checking /v2/rhel7/etcd/blobs/sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0085] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0085] ... already exists                           
Copying blob sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab
DEBU[0085] Downloading /v2/rhel7/etcd/blobs/sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0085] GET https://registry.access.redhat.com/v2/rhel7/etcd/blobs/sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0087] Detected compression format gzip             
 0 B / ? [--------------------------------------------------------------------=]DEBU[0087] Using original blob without modification     
DEBU[0087] Checking /v2/rhel7/etcd/blobs/sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0087] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
DEBU[0087] ... already exists                           
DEBU[0087] Consuming rest of the original blob to satisfy getOriginalLayerCopyWriter 
 14.31 MB / ? [----------------------------=-------------------------------] 9s 
DEBU[0096] Computed DiffID sha256:acff9253c91e74690aa64d0abbceff06fafb4140acdfe0fceb4c7006fd0e7428 for layer sha256:d2365ea888622f84a07a68ccd26c9a81b32242fe624f7b979ce30c2399a750ab 
Copying config sha256:797a818d8f9e3393b8c44cde94bc2108530afa4adb119d81166e7a69dbd4ad1e
DEBU[0096] No compression detected                      
 0 B / 7.67 KB [---------------------------------------------------------------]DEBU[0096] Using original blob without modification     
DEBU[0096] Checking /v2/rhel7/etcd/blobs/sha256:797a818d8f9e3393b8c44cde94bc2108530afa4adb119d81166e7a69dbd4ad1e 
DEBU[0096] HEAD https://registry.example.com:5000/v2/rhel7/etcd/blobs/sha256:797a818d8f9e3393b8c44cde94bc2108530afa4adb119d81166e7a69dbd4ad1e 
DEBU[0096] ... already exists                           
 0 B / 7.67 KB [------------------------------------------------------------] 0s
Writing manifest to image destination
DEBU[0096] PUT https://registry.example.com:5000/v2/rhel7/etcd/manifests/latest 
Storing signatures
[root@localhost ~]# 
```

Thanks.

**Comment by mtrmac** [comment] 2017-10-26 00:24
> This issue was filed exactly about what was demonstrated above so I'm not sure do we need another issue?

Because
> Ordinarily pre-existing layers should not be redundantly copied, at least as long as the destination can tell the client that the layer is already present.
>
> This issue seems more focused on the overhead of copying configs & manifests, and the overhead necessary to even avoid determining that the layers are already present.

**Comment by mtrmac** [comment] 2017-10-26 00:27
> This issue was filed exactly about what was demonstrated above so I'm not sure do we need another issue?

Because
> Ordinarily pre-existing layers should not be redundantly copied, at least as long as the destination can tell the client that the layer is already present.
>
> This issue seems more focused on the overhead of copying configs & manifests, and the overhead necessary to even avoid determining that the layers are already present.

… and fixing the broken layer deduplication which is _already_ supposed to be working, and writing new code to avoid a copy of the entire image only by checking that the manifest is present, are quite different tasks.

Filed https://github.com/containers/image/issues/367 , please let’s discuss that there.

**Comment by rhatdan** [comment] 2019-04-25 12:07
I believe this is fixed in the current skopeo.  Reopen if I am mistaken

**Closed by rhatdan** 2019-04-25 12:07 UTC

**Comment by mtrmac** [comment] 2019-04-25 15:56
Not _quite_, we still do the existence check layer by layer, but with the blob info cache it might be good enough.
