### ISSUE TITLE
Copying image from rootless -> rootfull container storage breaks rootless podman

### ISSUE THREAD

**Issue by akhilles** [containers/skopeo#1691] opened 2022-06-27 04:57 UTC
To reproduce:

Copy image from rootless container storage (`$HOME/.local/share/containers/storage`) to root container storage (`/var/lib/containers/storage`):

```
$ sudo skopeo copy containers-storage:[btrfs@$HOME/.local/share/containers/storage]localhost/image:latest containers-st
orage:localhost/image:latest
```

Then try using rootless podman normally:
```
$ podman ps
Error: chown /home/user/.local/share/containers/storage/btrfs: operation not permitted
```

I don't think it's a driver issue. I'm able to reproduce with `overlay` as well.

Additional context:
```
$ skopeo --version
skopeo version 1.8.0
$ podman --version
podman version 4.1.1
```

It looks like skopeo is changing the ownership of `~/.local/share/containers/storage/btrfs` from user to root. When I change it back manually, rootless podman commands work fine. But when I run the skopeo command, the ownership is changed back to root.

**Comment by mtrmac** [comment] 2022-06-27 16:30
Thanks for your report.

This is not reasonably possible to handle in a single process like Skopeo, because a single process can either be, or not be, in a user namespace; so it’s not possible to be able to correctly read from a rootless repository and write to a root one immediately.

It would be necessary to separate the two storage accesses into separate processes and let them communicate using some kind of IPC mechanism — something Skopeo otherwise doesn’t need to do. But that already exists in Podman, as `podman image scp`. So I’d recommend using that.

**Comment by rhatdan** [comment] 2022-06-27 17:26
Yes this is what podman image scp was designed for.  Closing this issue.

**Closed by rhatdan** 2022-06-27 17:26 UTC
