### ISSUE TITLE
Skopeo sync fails with 400 (Bad Request) on Quay.io (deeply nested repo name + bad error handling)

### ISSUE THREAD

**Issue by Drewster727** [containers/skopeo#1180] opened 2021-02-01 02:10 UTC
Hello,

I'm trying to sync some images from docker.io to my private registry, but am seeing a strange issue that I am confused by:

```
skopeo sync --src docker --dest docker docker.io/library/ubuntu:latest registry.local.com/drew/ubuntu --override-os linux --debug
```

Output
```
INFO[0000] Tag presence check                            imagename="docker.io/library/ubuntu:latest" tagged=true
DEBU[0000] Destination for transport "docker": //registry.local.com/drew/ubuntu/ubuntu:latest
INFO[0000] Copying image ref 1/1                         from="docker://ubuntu:latest" to="docker://registry.local.com/drew/ubuntu/ubuntu:latest"
DEBU[0000] Returning credentials from /Users/drew/.config/containers/auth.json
DEBU[0000] Using registries.d directory /usr/local/etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]   Using file:///var/lib/containers/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/registry.local.com
DEBU[0000] Loading registries configuration "/usr/local/etc/containers/registries.conf"
DEBU[0000] Trying to access "docker.io/library/ubuntu:latest"
DEBU[0000] Credentials not found
DEBU[0000] Using registries.d directory /usr/local/etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]  No signature storage configuration found for docker.io/library/ubuntu:latest, using built-in default file:///Users/drew/.local/share/containers/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io
DEBU[0000] GET https://registry-1.docker.io/v2/
DEBU[0000] Ping https://registry-1.docker.io/v2/ status 401
DEBU[0000] GET https://auth.docker.io/token?scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io
DEBU[0000] GET https://registry-1.docker.io/v2/library/ubuntu/manifests/latest
DEBU[0000] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.list.v2+json"
DEBU[0000] Using blob info cache at /Users/drew/.local/share/containers/cache/blob-info-cache-v1.boltdb
DEBU[0000] Source is a manifest list; copying (only) instance sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e for current system
DEBU[0000] GET https://registry-1.docker.io/v2/library/ubuntu/manifests/sha256:3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e
DEBU[0000] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.v2+json"
DEBU[0000] IsRunningImageAllowed for image docker:docker.io/library/ubuntu:latest
DEBU[0000]  Using default policy section
DEBU[0000]  Requirement 0: allowed
DEBU[0000] Overall: allowed
Getting image source signatures
DEBU[0000] Reading /Users/drew/.local/share/containers/sigstore/library/ubuntu@sha256=3093096ee188f8ff4531949b8f6115af4747ec1c58858c091c8cb4579c39cc4e/signature-1
DEBU[0000] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v1+json]
DEBU[0000] ... will first try using the original manifest unmodified
DEBU[0000] Checking /v2/drew/ubuntu/ubuntu/blobs/sha256:f611acd52c6cad803b06b5ba932e4aabd0f2d0d5a4d050c81de2832fcb781274
DEBU[0000] GET https://registry.local.com/v2/
DEBU[0000] Checking /v2/drew/ubuntu/ubuntu/blobs/sha256:83ee3a23efb7c75849515a6d46551c608b255d8402a4d3753752b88e0dc188fa
DEBU[0000] Checking /v2/drew/ubuntu/ubuntu/blobs/sha256:db98fc6f11f08950985a203e07755c3262c680d00084f601e7304b768c83b3b1
DEBU[0001] Ping https://registry.local.com/v2/ status 401
DEBU[0001] GET https://registry.local.com/v2/auth?account=drew&scope=repository%3Adrew%2Fubuntu%2Fubuntu%3Apull%2Cpush&service=registry.local.com
DEBU[0001] GET https://registry.local.com/v2/auth?account=drew&scope=repository%3Adrew%2Fubuntu%2Fubuntu%3Apull%2Cpush&service=registry.local.com
DEBU[0001] GET https://registry.local.com/v2/auth?account=drew&scope=repository%3Adrew%2Fubuntu%2Fubuntu%3Apull%2Cpush&service=registry.local.com
FATA[0001] Error copying ref "docker://ubuntu:latest": Error trying to reuse blob sha256:83ee3a23efb7c75849515a6d46551c608b255d8402a4d3753752b88e0dc188fa at destination: Requesting bear token: invalid status code from registry 400 (Bad Request)
```

I have full access to push to the private registry. I do so on a regular basis via docker push.  It is a Quay registry, and I have made sure that docker login succeeds prior to sync/push.

Have also just shortened the source path:
```
skopeo sync --src docker --dest docker ubuntu:latest registry.local.com/drew/ubuntu --override-os linux --debug
```

I've tried adding `--dest-creds` and the flags to ignore TLS just as a test. No bueno.

It seems a skopeo copy does work... which I find odd.

```
skopeo copy docker://ubuntu:latest docker://registry.local.com/drew/ubuntu:latest --override-os linux
```
Copy works... sync doesn't...

How can I diagnose what's going on here?

skopeo v1.2.1
Source: DockerHub (docker.io)
Destination: Quay v3.3.4 (private registry, registry.local.com)

**Comment by vrothberg** [comment] 2021-02-01 10:36
Thanks for reaching out @Drewster727.  This is curious and I can't yet put a finger on something specific.

Do you have access to the logs of your Quay registry?

@mtrmac, thought?

**Comment by mtrmac** [comment] 2021-02-01 14:45
I don’t think it’s “copy works / sync doesn’t”, something fails in the reuse path (after copying some data for the first time, we have a record that it exists on the destination and try to avoid copying again). To make the testing reproducible, you can get to a clean state by removing the `blob-info-cache-v1.boltdb` file listed in the debug log (and trigger the reuse path by copying the same image to a different repo on the same registry).

As for diagnosis, I’d suggest either server-side logs, or a HTTP trace using something like Wireshark or https://github.com/containers/image/pull/201 .

**Comment by Drewster727** [comment] 2021-02-01 14:53
I'll see if I can get quay registry server-side logs. 
@mtrmac I removed that `.boltdb` file, ran it again, same issue.
Also, tried a clean-slate and ran skopeo inside docker (no cached files, etc), same problem.

**Comment by mtrmac** [comment] 2021-02-01 15:12
… actually, this is probably not the full reuse path (those errors are non-fatal), it’s just the existence checks (basically the very first accesses) causing the first authentication attempts, and those fail. Wrong credentials (I’d expect a different error)? Some kind of rate limit?

**Comment by jensfr** [comment] 2021-02-09 14:18
FWIW, I saw the same error when I tried to push an image to a repository in quay.io which I had created just before. So on the first push.

```
STEP 1: FROM golang:latest AS builder
STEP 2: WORKDIR /go/src/kata-pod-annotate
STEP 3: COPY ../vendor ./
STEP 4: COPY . ./
STEP 5: RUN CGO_ENABLED=0 go build -o /go/bin/kata-pod-annotate
STEP 6: FROM alpine:latest
STEP 7: COPY --from=builder /go/bin/kata-pod-annotate /kata-pod-annotate
STEP 8: ENTRYPOINT ["/kata-pod-annotate"]
STEP 9: COMMIT quay.io/jensfr/kata-webhook/webhook:4.8
--> 81fb51b304d
81fb51b304dd7ad66779f6e3f1d3a5788699cf3d48ac4f29e41e6ed56024918

#> podman login -u jensfr quay.io
Password: 
Login Succeeded!
podman push quay.io/jensfr/kata-webhook/webhook:4.8
Getting image source signatures
Error: error copying image to the remote destination: Error trying to reuse blob sha256:d895afa5e47e063eeca38e005b0e271f65a40c27e95179a6eeab8a3323699c9a at destination: Requesting bear token: invalid status code from registry 400 (Bad Request)
```

```
#> podman version
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.14.10
Built:        Tue Dec  8 15:37:43 2020
OS/Arch:      linux/amd64
```

**Comment by djohnston89** [comment] 2021-04-30 02:56
@Drewster727 was this ever solved?

**Comment by frvge** [comment] 2021-07-14 12:35
The interesting part is that indeed, copy works, but sync often gives an authentication-like error it seems.


SYNC:
```
skopeo sync --src docker --dest docker --debug --all --src-no-creds --dest-authfile int.json MY.SOURCE.COM/
public_mirror/alpine MY.REGISTRY.COM/mirror_test/alpine
```

Quay log:
```
nginx stdout | 10.117.8.255 () - - [14/Jul/2021:12:23:46 +0000] "GET /v2/ HTTP/1.1" 401 4 "-" "skopeo/1.3.1" (0.002 173 0.002)
gunicorn-registry stdout | 2021-07-14 12:23:46,803 [573] [INFO] [gunicorn.access] 10.117.8.255 - - [14/Jul/2021:12:23:46 +0000] "GET /v2/ HTTP/1.1" 401 4 "-" "skopeo/1.3.1"
nginx stdout | 10.117.8.255 () - mirror_test+mirror_test_robot [14/Jul/2021:12:23:47 +0000] "GET /v2/auth?account=mirror_test%2Bmirror_test_robot&scope=repository%3Amirror_test%2Falpine%2Falpine%3Apull%2Cpush&service=MY.REGISTRY.COM HTTP/1.1" 400 133 "-" "skopeo/1.3.1" (0.009 422 0.009)
gunicorn-registry stdout | 2021-07-14 12:23:47,046 [572] [INFO] [gunicorn.access] 10.117.8.255 - mirror_test+mirror_test_robot [14/Jul/2021:12:23:47 +0000] "GET /v2/auth?account=mirror_test%2Bmirror_test_robot&scope=repository%3Amirror_test%2Falpine%2Falpine%3Apull%2Cpush&service=MY.REGISTRY.COM HTTP/1.1" 400 133 "-" "skopeo/1.3.1"
2021-07-14 12:23:47,046 [563] [INFO] [gunicorn.access] 10.117.8.255 - mirror_test+mirror_test_robot [14/Jul/2021:12:23:47 +0000] "GET /v2/auth?account=mirror_test%2Bmirror_test_robot&scope=repository%3Amirror_test%2Falpine%2Falpine%3Apull%2Cpush&service=MY.REGISTRY.COM HTTP/1.1" 400 133 "-" "skopeo/1.3.1"
nginx stdout | 10.117.8.255 () - mirror_test+mirror_test_robot [14/Jul/2021:12:23:47 +0000] "GET /v2/auth?account=mirror_test%2Bmirror_test_robot&scope=repository%3Amirror_test%2Falpine%2Falpine%3Apull%2Cpush&service=MY.REGISTRY.COM HTTP/1.1" 400 133 "-" "skopeo/1.3.1" (0.009 422 0.009)
```

skopeo debug:
```
... snip ...
DEBU[0001] Checking if we can skip copying: has signatures=false, OCI encryption=false, no manifest updates=false
DEBU[0001] Checking /v2/mirror_test/alpine/alpine/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
DEBU[0001] GET https://MY.REGISTRY.COM/v2/
DEBU[0001] Checking /v2/mirror_test/alpine/alpine/blobs/sha256:8e402f1a9c577ded051c1ef10e9fe4492890459522089959988a4852dee8ab2c
DEBU[0001] Ping https://MY.REGISTRY.COM/v2/ status 401
DEBU[0001] GET https://MY.REGISTRY.COM/v2/auth?account=mirror_test%2Bmirror_test_robot&scope=repository%3Amirror_test%2Falpine%2Falpine%3Apull%2Cpush&service=MY.REGISTRY.COM
DEBU[0001] GET https://MY.REGISTRY.COM/v2/auth?account=mirror_test%2Bmirror_test_robot&scope=repository%3Amirror_test%2Falpine%2Falpine%3Apull%2Cpush&service=MY.REGISTRY.COM
FATA[0001] Error copying ref "docker://MY.SOURCE.COM/public_mirror/alpine:3.9.2": Error trying to reuse blob sha256:8e402f1a9c577ded051c1ef10e9fe4492890459522089959988a4852dee8ab2c at destination: Requesting bear token: invalid status code from registry 400 (Bad Request)
```


COPY:
```
skopeo copy --debug --all --src-no-creds --dest-authfile int.json docker://MY.SOURCE.COM/public_mirror/alpi
ne:latest docker://MY.REGISTRY.COM/mirror_test/alpine:latest
```

Quay log:
```
nginx stdout | 10.117.8.255 () - - [14/Jul/2021:12:27:26 +0000] "GET /v2/ HTTP/1.1" 401 4 "-" "skopeo/1.3.1" (0.002 173 0.002)
gunicorn-registry stdout | 2021-07-14 12:27:26,628 [563] [INFO] [gunicorn.access] 10.117.8.255 - - [14/Jul/2021:12:27:26 +0000] "GET /v2/ HTTP/1.1" 401 4 "-" "skopeo/1.3.1"
nginx stdout | 10.117.8.255 () - mirror_test+mirror_test_robot [14/Jul/2021:12:27:26 +0000] "GET /v2/auth?account=mirror_test%2Bmirror_test_robot&scope=repository%3Amirror_test%2Falpine%3Apull%2Cpush&service=MY.REGISTRY.COM HTTP/1.1" 200 1115 "-" "skopeo/1.3.1" (0.038 413 0.038)
gunicorn-registry stdout | 2021-07-14 12:27:26,886 [563] [INFO] [gunicorn.access] 10.117.8.255 - mirror_test+mirror_test_robot [14/Jul/2021:12:27:26 +0000] "GET /v2/auth?account=mirror_test%2Bmirror_test_robot&scope=repository%3Amirror_test%2Falpine%3Apull%2Cpush&service=MY.REGISTRY.COM HTTP/1.1" 200 1115 "-" "skopeo/1.3.1"
nginx stdout | 10.117.8.255 () - - [14/Jul/2021:12:27:27 +0000] "HEAD /v2/mirror_test/alpine/blobs/sha256:5843afab387455b37944e709ee8c78d7520df80f8d01cf7f861aae63beeddb6b HTTP/1.1" 200 0 "-" "skopeo/1.3.1" (0.013 1373 0.013)
gunicorn-registry stdout | 2021-07-14 12:27:27,113 [563] [INFO] [gunicorn.access] 10.117.8.255 - - [14/Jul/2021:12:27:27 +0000] "HEAD /v2/mirror_test/alpine/blobs/sha256:5843afab387455b37944e709ee8c78d7520df80f8d01cf7f861aae63beeddb6b HTTP/1.1" 200 0 "-" "skopeo/1.3.1"
nginx stdout | 10.117.8.255 () - - [14/Jul/2021:12:27:28 +0000] "HEAD /v2/mirror_test/alpine/blobs/sha256:d4ff818577bc193b309b355b02ebc9220427090057b54a59e73b79bdfe139b83 HTTP/1.1" 200 0 "-" "skopeo/1.3.1" (0.013 1373 0.013)
gunicorn-registry stdout | 2021-07-14 12:27:28,037 [563] [INFO] [gunicorn.access] 10.117.8.255 - - [14/Jul/2021:12:27:28 +0000] "HEAD /v2/mirror_test/alpine/blobs/sha256:d4ff818577bc193b309b355b02ebc9220427090057b54a59e73b79bdfe139b83 HTTP/1.1" 200 0 "-" "skopeo/1.3.1"
gunicorn-registry stdout | 2021-07-14 12:27:28,344 [563] [INFO] [gunicorn.access] 10.117.8.255 - - [14/Jul/2021:12:27:28 +0000] "PUT /v2/mirror_test/alpine/manifests/latest HTTP/1.1" 202 2 "-" "skopeo/1.3.1"
```

**Comment by mtrmac** [comment] 2021-07-14 17:40
@frvge thanks for the logs, that helped pinpoint the difference. This actually looks like a CLI invocation problem:
```
nginx stdout | 10.117.8.255 () - mirror_test+mirror_test_robot [14/Jul/2021:12:23:47 +0000] "GET /v2/auth?account=mirror_test%2Bmirror_test_robot&scope=repository%3Amirror_test%2Falpine%2Falpine%3Apull%2Cpush&service=MY.REGISTRY.COM HTTP/1.1" 400 133 "-" "skopeo/1.3.1" (0.009 422 0.009)
```
vs.
```
nginx stdout | 10.117.8.255 () - mirror_test+mirror_test_robot [14/Jul/2021:12:27:26 +0000] "GET /v2/auth?account=mirror_test%2Bmirror_test_robot&scope=repository%3Amirror_test%2Falpine%3Apull%2Cpush&service=MY.REGISTRY.COM HTTP/1.1" 200 1115 "-" "skopeo/1.3.1" (0.038 413 0.038)
```

Note the different scope= value: the successful one uses `mirror_test/alpine`, the failing one `mirror_test/alpine/alpine`.

The meaning of source/destination arguments to `skopeo copy` and `skopeo sync` is different, compare https://github.com/containers/skopeo/blob/main/docs/skopeo-sync.1.md#synchronizing-to-a-container-registry-keeping-the-repository , and maybe #854 and other discussions about the `sync` syntax. Sadly we can’t just change it.

---

@Drewster727 looking more closely at your logs, this seems to be the same issue:
```
DEBU[0000] Destination for transport "docker": //registry.local.com/drew/ubuntu/ubuntu:latest
```
(doubled `ubuntu`) vs. `skopeo copy … docker://registry.local.com/drew/ubuntu:latest` (single `ubuntu`).

**Comment by mtrmac** [comment] 2021-07-14 17:50
Note to self: This should probably, after the cause is confirmed, be a RFE to c/image/docker error handling.

An example error body:
```
DEBU[0001] GET https://quay.io/v2/auth?account=mitr&scope=repository%3Amitr%2Ffedora-test%2Ffoo%3Apull%2Cpush&service=quay.io 
ERRO[0002] ===RES===
HTTP/1.1 400 BAD REQUEST
Connection: close
Content-Length: 128
Content-Type: application/json
Date: Wed, 14 Jul 2021 17:46:09 GMT
Server: nginx/1.12.1

{"errors":[{"code":"NAME_INVALID","detail":{},"message":"Nested repositories are not supported. Found: mitr/fedora-test/foo"}]}

===RES=== 
```
This is actually quite helpful… apart from the issue that the `errors` JSON format is not _formally_ specified for the token endpoint, AFAICS. Still, maybe there’s precedent for parsing it that way, or arguably we should special-case it anyway.

**Comment by frvge** [comment] 2021-07-14 18:03
After removing the repository/image name in the destination, it succeeds.

**Comment by iblancasa** [comment] 2021-09-14 17:53
Hi! Same issue here. I just wanted to mention that providing the `--scoped` makes it fail even with the workaround provided by @frvge

**Comment by ketank-new** [comment] 2021-11-11 05:08
encountering similar issue with podman push .. when trying to push the image to quay.io

Error: error copying image to the remote destination: Error trying to reuse blob sha256:2f5e7949c0b3e61e85e7eef9b03dab3b844b1cdd6c6e4d3c7bc643ff15692048 at destination: Requesting bear token: invalid status code from registry 400 (Bad Request)


any known fix for this?

**Comment by dosmanak** [comment] 2022-01-11 14:35
I've encoutered similar issue with podman pushing to gitlab container registry. Job retry is helping so far.
```
Error: trying to reuse blob sha256:8d3ac3489996423f53d6087c81180006263b79f206d3fdec9e66f0e27ceb8759 at destination: Requesting bear token: invalid status code from registry 404 (Not Found)
```

**Comment by mtrmac** [comment] 2022-01-11 15:48
This issue is for the `400` `"message":"Nested repositories are not supported. Found: mitr/fedora-test/foo"` message.

Please report/track intermittent 404 separately.

**Comment by paulpog-checkit** [comment] 2022-09-16 10:08
any progress on this?
I'n getting same with AWS ECR on sync

**Comment by mtrmac** [comment] 2022-09-16 15:28
@paulpog-checkit https://github.com/containers/skopeo/issues/1180#issuecomment-1010094264

---

I _think_ this should be fixed by https://github.com/containers/image/pull/1299 , but I can not immediately verify that, because the public Quay.io instance now accepts nested repo names.

**Comment by mtrmac** [comment] 2022-10-12 21:33
#1522 now includes the better error handling.

**Closed by mtrmac** 2022-10-12 21:33 UTC
