### ISSUE TITLE
docker registry support broken

### ISSUE THREAD

**Issue by hallyn** [containers/skopeo#419] opened 2017-09-15 15:03 UTC
Hi,

skopeo copy docker://fedora:24 dir:fedora-24
skopeo copy docker://ubuntu loci:ubuntu:latest

no longer work.  @cyphar found this is due to the new 'multiple architecture image' support in the docker registry.

**Comment by cyphar** [comment] 2017-09-15 21:35
Effectively the larger issue is that we need to figure out how we're going to handle multi-arch. If we just do a full conversion to OCI there's a overhead of downloading the layers for every arch, and `umoci` currently doesn't support saying "extract the `amd64` image under this multi-arch tag" -- mainly because multi-arch doesn't actually make a lot of sense in the first place. I can work on the `umoci` problems but this runs into the generic problem of "what are we meant to do when filtering the ManifestList tree".

**Comment by runcom** [comment] 2017-09-15 21:58
@cyphar @hallyn we're working on this /cc @mtrmac

**Comment by mtrmac** [comment] 2017-09-15 22:30
This is worked around in `master` (#417), I’m working on a larger fix.

> Effectively the larger issue is that we need to figure out how we're going to handle multi-arch.

Yeah.  Several of the c/image transports are incapable of multiple images (e.g. having a single manifest by definition, or being tied to the current architecture, like `docker-daemon:`); it’s conceptually easy enough to just choose a single manifest out of a the manifest list, and then copy that image instance. I’m working on that now.

If a destination does support manifest lists or something similar, it seems plausible that `copy.Image` would by default just copy all instances (probably allowing callers to opt for a single instance), and also upload a manifest list (the original, or a necessarily updated copy), taking care to only copy the shared blobs once. With a reasonably careful implementation the `copy.Image` can copy a manifest list wholesale without necessarily understanding anything about the architecture/platform qualifications (e.g. the scary OCI capabilities are not a blocker).

That doesn’t really say what to do in with OCI indexes… tentatively:
- We are not going to support signing manifest lists, at least not initially, only the individual manifest instances. That will allow copying a single instance out of the list elsewhere with matching signatures, and it will also let us freely edit the manifest list when copying the image.
- The current `oci/layout` implementation supports either a single-image index, or a multi-image index in which case the `…ref.name` annotation must be specified by the consumer. In that model, it seems simple enough to pretend that all images with the same `…ref.name` annotations represent a “manifest list” within a “repository”, and copy these images as a set. (I have no idea what the code should do if there are nested indexes or something like that, and I’ll be happy to leave worrying about that to someone else; as long as the code can handle a simple flat list, that’s good enough as far as I am concerned.)

Does that make sense?

**Comment by cyphar** [comment] 2017-09-17 00:06
@mtrmac 

> ... In that model, it seems simple enough to pretend that all images with the same …ref.name annotations represent a “manifest list” within a “repository”, and copy these images as a set.

What you would want is to use a nested manifest IMO. While duplicates are not disallowed by the OCI image spec, this just gets more ugly in my opinion for other implementations. But it's up to you, I'll have to handle it in `umoci` either way (and I think that on paper the multiple-tags problem has been solved in `umoci` `master` but I still need to write the architecture matching code).

> (I have no idea what the code should do if there are nested indexes or something like that, and I’ll be happy to leave worrying about that to someone else; as long as the code can handle a simple flat list, that’s good enough as far as I am concerned.)

`umoci` has a package that handles this for you, and we really should think about switching `containers/image`'s implementation to using `umoci`'s `oci/cas` and `oci/casext` packages.

**Comment by cyphar** [comment] 2017-09-18 02:57
> Why not contributing those pkgs in c/image though :angel:

Because only two of them would make sense in `c/image`, and I was hoping all the packages will end up in OCI (hell, I'm still hoping the whole of `umoci` will become an OCI project). At the moment I'm just keeping them in `umoci`, but I'm encouraging you to vendor them.

**Comment by mtrmac** [comment] 2017-09-18 13:37
> > ... In that model, it seems simple enough to pretend that all images with the same …ref.name annotations represent a “manifest list” within a “repository”, and copy these images as a set.
>
> What you would want is to use a nested manifest IMO.

I’m sorry, I was really focused only on how the generic copy pipeline would deal with the OCI indexes, and the point was primarily that the ability to present a subset of the index / a modified version of it to the generic copy pipeline means that the generic pipeline does not restrict OCI from implementing anything. Whether OCI ends up using a nested manifest or not was secondary to me; you’re right that a nested manifest looks cleaner.

> we really should think about switching `containers/image`'s implementation to using `umoci`'s `oci/cas` and `oci/casext` packages.

Yeah, maximizing code reuse and common interpretation of the spec would be great; I guess the contributors so far have found it easier to implement a small subset of the index reading/writing behavior from scratch, or didn’t know about `umoci`.

**Comment by purefn** [comment] 2017-10-24 00:03
Running into trying to pull an alpine image. It looks like #420 has a possible fix for this, but hasn't gotten much attention. In the meantime, is there a workaround?

**Comment by cyphar** [comment] 2017-10-24 03:35
#417 has a hotfix that should improve this -- the latest release (`0.1.24`) should contain that fix.

**Comment by purefn** [comment] 2017-10-24 03:49
I'm confused then. That looks like it explicitly does not support this. And I did try to use it and got the same error when trying to pull alpine:3.6.

**Comment by mtrmac** [comment] 2017-10-24 16:12
> That looks like it explicitly does not support this. 

Which “this” precisely do you mean?

> And I did try to use it and got the same error when trying to pull alpine:3.6.

What “same” error? On current master, `./skopeo --policy default-policy.json copy docker://alpine:3.6 dir:t` seems to work well enough. Please provide exact steps to reproduce and expected behavior.

**Comment by purefn** [comment] 2017-10-24 20:51
Aha, ok, that command does work. But this one 

```
skopeo copy docker://ubuntu@sha256:506e2d5852de1d7c90d538c5332bd3cc33b9cbd26f6
ca653875899c505c82687 docker-archive://h:ubuntu:latest
```

gives the error message

```
can not copy docker://ubuntu@sha256:506e2d5852de1d7c90d538c5332bd3cc33b9cbd26f6ca653875899c505c82687: manifest contains multiple images 
```

**Comment by mtrmac** [comment] 2017-10-25 19:28
Ah, right. That indeed needs #420 . The only workaround in the meantime would be to use the `@sha256:` digest of the relevant architecture-specific manifest instead of the digest of the manifest list.

**Comment by rhatdan** [comment] 2019-04-25 12:04
Since this was merged a while ago, I assume this issue is fixed.

**Closed by rhatdan** 2019-04-25 12:04 UTC

**Comment by mtrmac** [comment] 2019-04-25 16:08
Well, ultimately this was talking about https://github.com/containers/image/issues/400 as the 100% fix, but we don’t quite need a skopeo pointer to it that also deals with the urgent situation at that time.
