### ISSUE TITLE
How to use skopeo to delete images from ecr\gcr ? 

### ISSUE THREAD

**Issue by irispenker** [containers/skopeo#950] opened 2020-06-15 07:02 UTC
Hi ,
I have a containerized application which is using skopeo to copy images from internal build server to external repo in ECR and GCR.
It works like a charm. 
**I must mention that i am not using docker directly within the container - only skopeo.
So if you go to my container bash and type any docker command it will error that "docker not found" .**

So now i am trying to "delete" image from those ECR  with same user which i used to copy (allowed to all operations in that ECR registry) . BUT i get wired behavior : 

```
>>  skopeo --debug --tls-verify=false delete --creds=<user:password> docker://account-id.dkr.ecr.region.amazonaws.com/repo-name/image-name:tag

DEBU[0000] Returning credentials from DockerAuthConfig
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]   Using file:///var/lib/containers/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/account-id.dkr.ecr.region.amazonaws.com
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0000] GET https://account-id.dkr.ecr.region.amazonaws.com/v2/
DEBU[0000] Ping https://account-id.dkr.ecr.region.amazonaws.com/v2/ status 401
DEBU[0000] GET https://account-id.dkr.ecr.region.amazonaws.com/v2/repo-name/image-name/manifests/tag
DEBU[0001] DELETE https://account-id.dkr.ecr.region.amazonaws.com/v2/repo-name/image-name/manifests/
FATA[0002] Failed to delete /v2/repo-name/image-name/manifests/: 404 page not found
```

And with digest : 

```
>>  skopeo --debug --tls-verify=false delete --creds=<user:password> docker://account-id.dkr.ecr.region.amazonaws.com@sha256:digest

first i got this : 
DEBU[0000] Returning credentials from DockerAuthConfig
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]   Using file:///var/lib/containers/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0000] GET https://registry-1.docker.io/v2/
DEBU[0000] Ping https://registry-1.docker.io/v2/ status 401
DEBU[0000] GET https://auth.docker.io/token?account=AWS&scope=repository%3Alibrary%2Faccount-id.dkr.ecr.region.amazonaws.com%3A%2A&service=registry.docker.io
FATA[0001] Get https://auth.docker.io/token?account=AWS&scope=repository%3Alibrary%2Faccount-id.dkr.ecr.region.amazonaws.com%3A%2A&service=registry.docker.io: remote error: tls: bad record MAC

Then i got this : 
DEBU[0000] Returning credentials from DockerAuthConfig
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]   Using file:///var/lib/containers/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0000] GET https://registry-1.docker.io/v2/
DEBU[0000] Ping https://registry-1.docker.io/v2/ status 401
DEBU[0000] GET https://auth.docker.io/token?account=AWS&scope=repository%3Alibrary%2Faccount-id.dkr.ecr.region.amazonaws.com%3A%2A&service=registry.docker.io
FATA[0001] unable to retrieve auth token: invalid username/password: unauthorized: incorrect username or password
```

Can someone help with the exact instruction to what should be done to make this work ?

**Comment by mtrmac** [comment] 2020-06-15 12:29
In the future, please don’t post the same question to all those places.

The first problem is #819.  The second is caused by invalid syntax, the format should be `docker://account-id.dkr.ecr.region.amazonaws.com/repo-name/image-name@sha256:digest`, not `docker://account-id.dkr.ecr.region.amazonaws.com@sha256:digest`.

**Comment by mtrmac** [comment] 2020-08-08 02:29
@irispenker Were you able to make this work?

**Comment by rhatdan** [comment] 2020-10-08 17:04
Closing for lack of information and I think we have another issue covering this use case.

**Closed by rhatdan** 2020-10-08 17:04 UTC
