### ISSUE TITLE
Fail to decrypt the image with PKCS7

### ISSUE THREAD

**Issue by wlei27** [containers/skopeo#1320] opened 2021-06-18 01:25 UTC
I build the skopeo version v1.2.3 and version 1.3.1-dev commit: dde3e759f6beda3f586896245fd8ca74ad15c7eb from the source codes.  Then I used them to decrypt the image with PKCS7, but I get the failure for both of them. 
Then I switch to build the version v1.2.2, and I can run the decryption successfully.
Here are the details about my decryption failure with my built v1.2.3.
```
[root@oc2587580306 skopeo]# uname -a
Linux oc2587580306.ibm.com 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@oc2587580306 skopeo]# 

## Generate the certification first  ##

[root@oc2587580306 skopeo]# openssl genrsa -out myjwekey.pem 2048
Generating RSA private key, 2048 bit long modulus
..................................+++
....................+++
e is 65537 (0x10001)
[root@oc2587580306 skopeo]# openssl req -new -sha256 -key myjwekey.pem -out myjwekey.csr
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [XX]:cn
State or Province Name (full name) []:beijing
Locality Name (eg, city) [Default City]:beijing
Organization Name (eg, company) [Default Company Ltd]:ibm
Organizational Unit Name (eg, section) []:csl
Common Name (eg, your name or your server's hostname) []:lei
Email Address []:

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
[root@oc2587580306 skopeo]# openssl x509 -req -sha256 -days 365 -in myjwekey.csr -signkey myjwekey.pem -out mykey_x509.crt
Signature ok
subject=/C=cn/ST=beijing/L=beijing/O=ibm/OU=csl/CN=lei
Getting Private key
[root@oc2587580306 skopeo]#

## Encrypt the image nginx ##
[root@oc2587580306 skopeo]# bin/skopeo  copy --encryption-key pkcs7:./mykey_x509.crt oci:local_nginx:latest oci:nginx_encrypted_x509:latest
Getting image source signatures
Copying blob 69692152171a done  
Copying blob 30afc0b18f67 done  
Copying blob 596b1d696923 done  
Copying blob febe5bd23e98 done  
Copying blob 8283eee92e2f done  
Copying blob 351ad75a6cfa done  
Copying config b96e6c32a3 done  
Writing manifest to image destination
Storing signatures
[root@oc2587580306 skopeo]#

## Decrypt the nginx ##
[root@oc2587580306 skopeo]# bin/skopeo copy --decryption-key ./mykey_x509.crt --decryption-key ./myjwekey.pem oci:nginx_encrypted_x509:latest oci:nginx_decrypted_x509:latest
Getting image source signatures
Copying blob e475facb2a01 [--------------------------------------] 0.0b / 25.9MiB
Copying blob fc1b2134900c [--------------------------------------] 0.0b / 25.3MiB
Copying blob 0a93445a8032 [--------------------------------------] 0.0b / 601.0b
Copying blob fe8a1bcb853a [--------------------------------------] 0.0b / 893.0b
Copying blob 56a80b6d17ee [--------------------------------------] 0.0b / 665.0b
Copying blob 92ca8c8917dd [--------------------------------------] 0.0b / 1.4KiB
FATA[0000] Error decrypting layer sha256:e475facb2a0186b1bdda2200e6fd77cb666f3f3e526f87d975d5c904dc5208d0: no suitable key unwrapper found or none of the private keys could be used for decryption:
no suitable key found for decrypting layer key:
- no x509 certificates found needed for PKCS7 decryption
 
[root@oc2587580306 skopeo]#
```

**Comment by lumjjb** [comment] 2021-06-18 14:57
@harche do you have any ideas what may have changed since 1.2.2 to break this? Any changing of passing arguments around?

**Comment by harche** [comment] 2021-06-21 09:32
Not sure. Maybe something changed in containers/storage? 

cc @vrothberg @mtrmac

**Comment by mtrmac** [comment] 2021-06-21 09:55
This is an OCI/OCI copy, c/storage is not involved at all. The “no suitable key unwrapper” message refers to concepts c/image is completely unaware of, it just provides raw data to the cryptography implementation.

So it’s tempting to point at github.com/containers/ocicrypt updating from v1.0.3 to  github.com/containers/ocicrypt v1.1.1 , but I didn’t even try to reproduce this yet.

**Comment by lumjjb** [comment] 2021-06-21 12:44
I will test the ocicrypt changes

**Comment by lumjjb** [comment] 2021-06-21 15:08
yea it looks like going into ocicrypt 1.1.0 broke something, let me investigate further

**Comment by lumjjb** [comment] 2021-06-21 15:25
Seemed to have found the issue, bad change in getting x509 certs from files, this will fix, and i'll create a new release.

```
-       if len(x509s) > 0 {
-               // x509 certs can also be passed in via keys
-               x509FromKeys, err := processx509Certs(keys)
-               if err != nil {
-                       return encconfig.CryptoConfig{}, err
-               }
-               x509s = append(x509s, x509FromKeys...)
+       // x509 certs can also be passed in via keys
+       x509FromKeys, err := processx509Certs(keys)
+       if err != nil {
+               return encconfig.CryptoConfig{}, err
        }
+       x509s = append(x509s, x509FromKeys...)
+
```

**Comment by lumjjb** [comment] 2021-06-28 18:44
This should now be fixed with https://github.com/containers/ocicrypt/releases/tag/v1.1.2

**Comment by mtrmac** [comment] 2021-06-29 14:56
#1344 was just merged; @wlei27 can you confirm this one works, please?

**Comment by wlei27** [comment] 2021-06-30 01:54
@mtrmac I rebuilt the skepeo with 1.3.1-dev commit: 71e7a5839ef6bed3e280742d916e073b465f6d81, and I can decrypt the image with PKCS7 now. Thanks!

**Comment by mtrmac** [comment] 2021-06-30 10:54
Great, thanks for the confirmation and @lumjjb thanks for the fix!

**Closed by mtrmac** 2021-06-30 10:54 UTC
