### ISSUE TITLE
--override-arch does not affect (skopeo inspect) digest output

### ISSUE THREAD

**Issue by nicop311** [containers/skopeo#1867] opened 2023-01-20 17:22 UTC
Can someone explain to me why the following digest results are different between `skopeo` and `crane`?

I do not understand if I can trust the `skope inspect` output. I see a lot of issues opened about digests.

I read [1555](https://github.com/containers/skopeo/pull/1555), but I still do not understand the philosophy.
I don't find this explanation satisfactory, or maybe I do not understand the purpose of `--override-arch`.

### get digests with Crane

**arm64/v8**

```bash
crane digest --platform="linux/arm64" docker.io/alpine:3.17.1
```
```
sha256:41d876d4e44348d1c27445fdb0e64592e0eb926d4dbbcf09a3526dee7e628329
```
with variant
```bash
crane digest --platform="linux/arm64/v8" docker.io/alpine:3.17.1
```
```
sha256:41d876d4e44348d1c27445fdb0e64592e0eb926d4dbbcf09a3526dee7e628329
```

Both command return the same digest `41d876d4e443`. This is the same we can see at https://hub.docker.com/_/alpine/tags .

**x86_64** AMD64

```bash
crane digest --platform="linux/amd64" docker.io/alpine:3.17.1
```
```
sha256:93d5a28ff72d288d69b5997b8ba47396d2cbb62a72b5d87cd3351094b5d578a0
```

Command returns a digest `93d5a28ff72d`. This is the same we can see at https://hub.docker.com/_/alpine/tags .

### get digests with Skopeo

**arm64/v8**

```bash
skopeo --override-os="linux" --override-arch="arm64" --override-variant="v8"  inspect --format="{{.Digest}}" docker://docker.io/alpine:3.17.1
```
```
sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a
```

The `skopeo` command returns a different digest than with `crane`. **I do not understand why the digests are different**.

**x86_64** AMD64

```bash
skopeo --override-os="linux" --override-arch="amd64"  inspect --format="{{.Digest}}" docker://docker.io/alpine:3.17.1
```
```
sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a
```

With `skopeo`, the digest returned by the command is the same with both AMD64 and ARM64. `--override-arch` does not seem to have any effect.
**I do not understand why the digests are the same for 2 different platforms ARM64 and AMD64**.

I have no idea what image this digest corresponds to `sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a`. I am not sure why I would get a "top manifest digest" (as per [1555](https://github.com/containers/skopeo/pull/1555)) when I set os, arch and variant.

However if you specify a digest with `skopeo`, for example if you use the digest `41d876d4e443` provided by `crane` above, then you get the expected digest.

```bash
skopeo inspect --format="{{.Digest}}" docker://docker.io/alpine@sha256:41d876d4e44348d1c27445fdb0e64592e0eb926d4dbbcf09a3526dee7e628329
```
```
sha256:41d876d4e44348d1c27445fdb0e64592e0eb926d4dbbcf09a3526dee7e628329
```

### On the DockerHub WEB GUI

The digests on the docker hub WEB GUI match the ones retrieved with `crane`.

https://hub.docker.com/_/alpine/tags

TAG [3.17.1](https://hub.docker.com/layers/library/alpine/3.17.1/images/sha256-93d5a28ff72d288d69b5997b8ba47396d2cbb62a72b5d87cd3351094b5d578a0?context=explore)

```
docker pull alpine:3.17.1
Last pushed 11 days ago by [doijanky](https://hub.docker.com/u/doijanky)

Digest         OS/ARCH          Compressed Size
14d4381342be   linux/386        3.25 MB
93d5a28ff72d   linux/amd64      3.21 MB
01a4cdaebc9c   linux/arm/v6     2.96 MB
1c34b3cb760a   linux/arm/v7     2.73 MB
41d876d4e443   linux/arm64/v8   3.11 MB
145b24ad7f65   linux/ppc64le    3.23 MB
176bc6c6e935   linux/s390x      3.02 MB
```

Notice `41d876d4e443` corresponds to `alpine:3.17.1` `linux/arm64/v8` full digest `sha256:41d876d4e44348d1c27445fdb0e64592e0eb926d4dbbcf09a3526dee7e628329` that was retrieved by `crane`.

## `skopeo inspect --raw`

When using option `--raw`, we get the list of all the digests above.

```bash
skopeo inspect docker://docker.io/alpine:3.17.1 --raw | jq | grep "41d876d4e443"
```
```
      "digest": "sha256:41d876d4e44348d1c27445fdb0e64592e0eb926d4dbbcf09a3526dee7e628329",
```

## CLI versions

```
$ crane version 
v0.12.1
```

```
$ skopeo --version
skopeo version 1.10.0 commit: ee60474d5a4d99745aac9855797ad4b26510d786
```

```
jq --version
jq-1.6
```

**Comment by mtrmac** [comment] 2023-01-20 18:36
Thanks for reaching out.

The digest of `skopeo inspect` is always the digest of the immediately requested object; if it is a multi-arch image, it’s the digest of the multi-arch manifest list.

`--override-arch` and the other `--override` options change what the “current runtime OS” is _if the operation depends on the current runtime OS_ (e.g. in this case it affects the layer set and `env`), but it, by design, does not change the _nature_ of the current operation, i.e. it does not change the semantics of the digest field in `skopeo inspect` to turn it from the digest of the requested object to a digest of a sub-object.

You are probably looking for some variant of #1283 , which has not yet been implemented.

**Comment by nicop311** [comment] 2023-01-20 20:58
Thank you for your quick reply. I understand your explanation. You probably agree that the behaviour of `skopeo inspect` in regards to those `skopeo` parameters about overriding arch, os and variant is not intuitive for the digest field. 

This makes me mentionned this other suggestion of adding a dedicated `skopeo digest` command, which works like the `crane digest` command. 
https://github.com/containers/skopeo/issues/1689


But another suggestion could be that `crane` should implement a `crane sync` command, which works like `skopeo sync`. Because I think that this is one major difference between the 2 tools (in term of features).

Indeed I am currently using both crane and skopeo at the same time to compensate for the feature one or the other lacks. Example: I get a digest from crane and I sync the image with skopeo. 

They have some similar features and distincts ones. But there are situations where you prefer to use only one tool (for convenience or simplicity), and because of the similarities you are tempted to think you can replace one with the other.

## what should we do next?

Do you think that this behavior (--overide-xyz not affecting skopeo inspect) should be changed for parameters like digest?

Or should this issue be closed, and the discussion continue with issues #1689 and #1283 ?

**Comment by mtrmac** [comment] 2023-01-20 21:12
The design of `--override-*` is, for better or worse, both intentional, and fixed by our desire not to break existing deployments.

So, yes, #1283 and/or #1689 would be the way forward.

**Closed** 2023-01-20 21:19 UTC
