### ISSUE TITLE
copy_test.go failures outside a specific container image in --privileged mode

### ISSUE THREAD

**Issue by cevich** [containers/skopeo#1222] opened 2021-03-11 14:29 UTC
At the time of filing this issue, the skopeo integration tests cannot pass outside [a `--privileged` quay.io auto-build image](https://quay.io/repository/skopeo/ci).  A dozen or so `copy_test.go` items fail similar to:

```
FAIL: copy_test.go:187: CopySuite.TestCopyWithManifestListStorage
Running skopeo copy docker://registry.fedoraproject.org/fedora-minimal containers-storage:[vfs@/tmp/copy-manifest-list-storage789817936/root+/tmp/copy-manifest-list-storage789817936/runroot]test
copy_test.go:198:
    assertSkopeoSucceeds(c, "", "copy", knownListImage, "containers-storage:"+storage+"test")
utils.go:62:
    c.Assert(err, check.IsNil, check.Commentf("%s", out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0004c2a40), Stderr:[]uint8(nil)} ("exit status 1")
... time="2021-03-04T17:00:15Z" level=warning msg="error reading allowed ID mappings: error reading subuid mappings for user \"root\" and subgid mappings for group \"root\": No subuid ranges found for user \"root\" in /etc/subuid"
time="2021-03-04T17:00:15Z" level=warning msg="Found no UID ranges set aside for user \"root\" in /etc/subuid."
time="2021-03-04T17:00:15Z" level=warning msg="Found no GID ranges set aside for user \"root\" in /etc/subgid."
Getting image source signatures
Copying blob sha256:2fa61fedb54d576e17d9129a27fbd3c1ff8503b1e0c45622ba8de6a51fb6a9ef
Copying config sha256:fa011f8784baff6b77fc56152b5024c368809c0f4c6b1279dbd9b173f534028a
Writing manifest to image destination
Storing signatures
time="2021-03-04T17:00:19Z" level=error msg="Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid: lchown /var/spool/mail: invalid argument"
time="2021-03-04T17:00:19Z" level=fatal msg="Error committing the finished image: error adding layer with blob \"sha256:2fa61fedb54d576e17d9129a27fbd3c1ff8503b1e0c45622ba8de6a51fb6a9ef\": ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid: lchown /var/spool/mail: invalid argument"
time="2021-03-04T17:00:19Z" level=error msg="exit status 1"
```

This can be reproduced as root or as a regular user (the errors appear the same) with the following commands on Fedora 33 VM:

```bash
export GOPATH=/var/tmp/go
export BUILDTAGS='btrfs_noversion libdm_no_deferred_remove'
export SKOPEO_PATH=$GOPATH/src/github.com/containers/skopeo
export "PATH=$SKOPEO_PATH/bin:$PATH:$GOPATH/bin"
mkdir -p $SKOPEO_PATH
git clone https://github.com/containers/skopeo $SKOPEO_PATH
cd $SKOPEO_PATH
make BUILDTAGS="${BUILDTAGS}" bin/skopeo
make BUILDTAGS="${BUILDTAGS}" test-integration
```

***note:*** The `test-integration` target further builds and executes inside a container image.

A fix for this is necessary, so that [temporary provisions for building and using this `skopeo/ci` container image under CI](https://github.com/containers/image/commit/9c64ce59a93fa37df792a35017f5e44f3971924e#diff-62587956f943bb2503db7bc6dd27d0d888074a1c0ecaab3f570ad611aff0f7bbR128-R136) may be removed.  For accurate/faithful automated testing, CI needs to be able to execute the tests (also) outside of a privileged container environment.  Otherwise, given time, these temporary provisions will likely lead to increased maintenance burden and hiding further test or skopeo bugs.

**Comment by mtrmac** [comment] 2022-06-06 14:11
For the most part, testing writes to c/storage does require `root`. It might be possible to re-configure it to run in a completely rootless mode (by squashing UIDs to the UID of the invoking user). https://github.com/containers/image/blob/6e363d2b40073004d59b623ad7928fd0dce39c0b/storage/storage_test.go#L63 does that at least for `root` (which doesn’t help for the failure above, with `12` in-container GID). Or maybe there are other useful c/storage options, `ignore_chown_errors` might be worth investigating.

**Comment by mtrmac** [comment] 2022-06-06 14:12
Actually… @cevich I’ll leave it up to you to say whether this should be reopened. Re-closing as the bot did, for now.

**Comment by mtrmac** [comment] 2022-06-06 21:05
Oh, `make integration` is completely broken. To an extent, the automated CI matters much more than the rest, but still, having broken `Makefile` target on the main developer path and breaking local development is quite a bad look. At the very least we should drop that target if we are not going to make it work.

---

The cause is that Skopeo’s “should I run in a user namespace” logic requires a set of capabilities: https://github.com/containers/skopeo/blob/eb61a79dde5d4d8f3ecb93bb93bedbcb3329663d/cmd/skopeo/unshare_linux.go#L11-L16 but new containers don’t have `cap_mknod` anymore.

Possible fixes:
- Re-add that capability: `podman run --cap-add=cap_mknod … make test-integration-local` . It’s, of course, up to a discussion whether that is any more valuable than requiring `--privileged`. (I know little enough about container isolation that I have no idea.) FWIW `make test-system` is still `--privileged`, and basically has to be so (it is running containers inside containers).
- Accept that these tests are going to run rootless, and make that possible: `echo 'root:100000:65536' > /etc/subuid ; echo 'root:100000:65536' > /etc/subgid` inside the container seems to work.
- (Decrease the set of required capabilities, so that a run in a container doesn’t require `cap_mknod`. While we could, probably, design tests that don’t require that capability, it seems likely that many other Skopeo uses of `containers-storage:` would indeed need it, so we wouldn’t be testing a production-configured Skopeo. That seems counterproductive.)

My very weak preference is to do the `--cap-add` change, because the inside of the container would be a bit more standard; `root` running rootless containers seems unusual. But I can see a case for the `subuid`/`subgid` approach, it makes it clearer that the tests run in an isolated environment..

---

(This, BTW, reveals that our integration tests only test rootful, or rootless, `containers-storage:` use, not both. I’m not _too_ worried about that — using Skopeo with c/storage directly is always a pain — but it is a gap.)

**Comment by cevich** [comment] 2022-06-06 21:20
Lol, yeah, I guess it's all a matter of perspective.  I guess if the environment is considered useful and likely for users, then we should probably do all three.  i.e. the tests should run directly on the VM *AND* as root inside a container, *AND* as rootless in a container.  Anyway FWIW, arranging for all three environments isn't much more than a little bit of YAML.  It sounds like fixing the test to run under these scenarios is the hard part.

**Comment by mtrmac** [comment] 2022-06-06 21:27
Well, `make test-integration` is purely a developer-targeted task… and you’re the only developer who has complained. So I don’t think it makes much sense to ~double the test time on every CI run just to keep this running.

WRT fixing the tests, I have tested that both `--cap-add=cap_mknod` and the `/etc/sub[ug]id` changes allow `test-integration` to pass. (The latter might affect `test-system`, which I didn’t try.) So I think now it’s a matter of choosing which one we want.

**Comment by mtrmac** [comment] 2023-01-20 18:11
#1864 will fix `make test-integration`, both when ran as `root` and as an unprivileged user.

`make test-system` fails, differently for non-privileged users (WIP) and for `root` (somehow networking between the container-in-container registry and the `test-system` container just hangs in my limited tests).

**Comment by mtrmac** [comment] 2023-01-20 19:22
… and #1868 fixes `make test-system`, for unprivileged users at least.

**Closed** 2023-01-23 09:06 UTC
Labels: bug
