### ISSUE TITLE
Error while writing manifest image to destination

### ISSUE THREAD

**Issue by fntlnz** [containers/skopeo#402] opened 2017-08-28 11:19 UTC
When trying to copy an image from a docker registry on an openshift cluster to another docker-registry on another openshift cluster I get the following error.

I get the same error by using different versions of skopeo, both built by me, using the official rpm on rhel and also using the `rhel-tools` image.

```
skopeo copy --src-tls-verify=false --src-creds any:**** --dest-tls-verify=false --dest-creds any:**** docker://docker-registry-default.cloudapps.someopenshiftcluster/someorg/someimage:v1.1.0-rc1 docker://docker-registry-default.cloudapps.someotherropenshiftcluster/someorg/someimage:prod
Getting image source signatures
Skipping fetch of repeat blob sha256:b25889d273102779a1d372b4e6590da9916fe594300bf1573cb9a6521a57c25e
Skipping fetch of repeat blob sha256:9161239f9b2210ead4fc1d528eb2167593dfe38c137c331e3dd19af0fc8cff39
Skipping fetch of repeat blob sha256:4c26e4312208e0356276c108178b55663c8a38fc1d17e90bcf7e5a18720e5412
Skipping fetch of repeat blob sha256:6bf86f3bfc19314da1db89b9530e4bece09caa1cefa81b06da08723a5ea2de68
Skipping fetch of repeat blob sha256:04cf1b47c5a0895b1cf295060efe04286370074a94f6971e5a8bdcd46f41fcd1
Skipping fetch of repeat blob sha256:1e5acd71f269e9ceb7067c5725ca952a8e9d0a391501443abdb0c420e7fd90bb
Skipping fetch of repeat blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Skipping fetch of repeat blob sha256:b1a67efc903ff1fe346457de4a6f05450ceee734d86a139b55dd4c7ee0c8bbfe
Skipping fetch of repeat blob sha256:78a76af193ea1ba85efe949c623d039cd8826eb490601da6bc576d749f08d323
Skipping fetch of repeat blob sha256:8ccced0f514a9ba05360dddc9fb5cfdd89e78f6d5ba3a0a9b7aa6a59c43ee0ec
Skipping fetch of repeat blob sha256:a21ad575749b51a87b4eccdc7a04a8a0084f7bf163d33902f5f7fdabdf87b3b3
Skipping fetch of repeat blob sha256:9288470e38de40b25b12e0df23188a3f7c5056d88523d388dd3c68c574b9ba53
Skipping fetch of repeat blob sha256:683ba06a68e23037b9d7f8ccb0b3c549aeeaacbc89b95402907cf494dd4a30cf
Skipping fetch of repeat blob sha256:065359ed5ca2e7fda126d07cf4cd9f574462b982838a509385dbae0a38a2d132
Skipping fetch of repeat blob sha256:500f7dff4dd0433ad4b16023d89045f39352e5be4c27153cc6b691e22c0f3351
Skipping fetch of repeat blob sha256:d1b259a4ee48604ec87cc764935d6f9df44816ec53a4d6c15151cadded323686
Skipping fetch of repeat blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Skipping fetch of repeat blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Skipping fetch of repeat blob sha256:56f97170027f7e2a5631e45fcc00559c2af5456ebfaa917427fd5ecdd36bafcb
Writing manifest to image destination
time="2017-08-28T11:31:26+02:00" level=fatal msg="Error writing manifest: Error uploading manifest to someorg/someimage/manifests/prod, status 500"
```

I even tried using `atomic:` for dest but same thing.

At this point I suspect that could be something related to the fact that the two OpenShift clusters are at different versions (and probably also the inner registries, I have to verify this). 

However I opened this issue to report that this is happening and also if it's related to different versions I think that skopeo should still work IMHO.

Anyway the 5xx errors are indicative that something is wrong with the server so there's a possibility that skopeo is just showing a problem that's happening at infrastructure level.

Pushing and pulling images with the docker client (the one in RHEL) works.

Setting as destination the same as source by just changing the tag WORKS.

Using skopeo to copy the image locally and then take that image and copy to the remote DOES NOT WORK.

Wdyt?

**Comment by runcom** [comment] 2017-08-28 11:50
Please run with --debug also and paste output, thanks

**Comment by fntlnz** [comment] 2017-08-28 12:47
Ok that command is showing that the actual problem is that the remote repo doesn't even exists (log below)

So one might ask: Worth checking if the remote repo exists before than trying to do that?

I don't think that this can be done since "non-atomic" registries like the default one in `docker/distribution` actually create the repository when you push it.

The strange thing is that it pushes the whole thing and just fail in writing the manifest while would probably be a more user friendly behavior to just deny the push like how it happens in docker hub:

```
$  docker push docker.io/fntlnz/cantpushere
The push refers to a repository [docker.io/fntlnz/cantpushere]
e58d31f33474: Preparing 
denied: requested access to the resource is denied

```



## That log you asked

```
+ skopeo --debug copy --src-tls-verify=false --src-creds any:**** --dest-tls-verify=false --dest-creds any:**** docker://docker-registry-default.cloudapps-test.mycompany.com/myorg/myrepoe:v1.1.0-rc1 docker://docker-registry-default.cloudapps.mycompany.com/myorg/myrepoe:prod
time="2017-08-28T14:33:11+02:00" level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration" 
time="2017-08-28T14:33:11+02:00" level=debug msg=" Using \"default-docker\" configuration" 
time="2017-08-28T14:33:11+02:00" level=debug msg="  Using file:///var/lib/atomic/sigstore" 
time="2017-08-28T14:33:11+02:00" level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration" 
time="2017-08-28T14:33:11+02:00" level=debug msg=" Using \"default-docker\" configuration" 
time="2017-08-28T14:33:11+02:00" level=debug msg=" No signature storage configuration found for docker-registry-default.cloudapps-test.mycompany.com/myorg/myrepoe:v1.1.0-rc1" 
time="2017-08-28T14:33:11+02:00" level=debug msg="IsRunningImageAllowed for image docker:docker-registry-default.cloudapps-test.mycompany.com/myorg/myrepoe:v1.1.0-rc1" 
time="2017-08-28T14:33:11+02:00" level=debug msg=" Using default policy section" 
time="2017-08-28T14:33:11+02:00" level=debug msg=" Requirement 0: allowed" 
time="2017-08-28T14:33:11+02:00" level=debug msg="Overall: allowed" 
time="2017-08-28T14:33:11+02:00" level=debug msg="GET https://docker-registry-default.cloudapps-test.mycompany.com/v2/" 
time="2017-08-28T14:33:11+02:00" level=debug msg="Ping https://docker-registry-default.cloudapps-test.mycompany.com/v2/ err <nil>" 
time="2017-08-28T14:33:11+02:00" level=debug msg="Ping https://docker-registry-default.cloudapps-test.mycompany.com/v2/ status 401" 
time="2017-08-28T14:33:11+02:00" level=debug msg="Increasing token expiration to: 60 seconds" 
time="2017-08-28T14:33:11+02:00" level=debug msg="GET https://docker-registry-default.cloudapps-test.mycompany.com/v2/myorg/myrepoe/manifests/v1.1.0-rc1" 
Getting image source signatures
time="2017-08-28T14:33:11+02:00" level=debug msg="Manifest MIME type application/vnd.docker.distribution.manifest.v1+prettyjws is declared supported by the destination" 
time="2017-08-28T14:33:11+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:b25889d273102779a1d372b4e6590da9916fe594300bf1573cb9a6521a57c25e" 
time="2017-08-28T14:33:11+02:00" level=debug msg="GET https://docker-registry-default.cloudapps.mycompany.com/v2/" 

time="2017-08-28T14:33:12+02:00" level=debug msg="Ping https://docker-registry-default.cloudapps.mycompany.com/v2/ err <nil>" 
time="2017-08-28T14:33:12+02:00" level=debug msg="Ping https://docker-registry-default.cloudapps.mycompany.com/v2/ status 401" 
time="2017-08-28T14:33:12+02:00" level=debug msg="Increasing token expiration to: 60 seconds" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:b25889d273102779a1d372b4e6590da9916fe594300bf1573cb9a6521a57c25e" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:b25889d273102779a1d372b4e6590da9916fe594300bf1573cb9a6521a57c25e
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:9161239f9b2210ead4fc1d528eb2167593dfe38c137c331e3dd19af0fc8cff39" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:9161239f9b2210ead4fc1d528eb2167593dfe38c137c331e3dd19af0fc8cff39" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:9161239f9b2210ead4fc1d528eb2167593dfe38c137c331e3dd19af0fc8cff39
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:4c26e4312208e0356276c108178b55663c8a38fc1d17e90bcf7e5a18720e5412" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:4c26e4312208e0356276c108178b55663c8a38fc1d17e90bcf7e5a18720e5412" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:4c26e4312208e0356276c108178b55663c8a38fc1d17e90bcf7e5a18720e5412
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:6bf86f3bfc19314da1db89b9530e4bece09caa1cefa81b06da08723a5ea2de68" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:6bf86f3bfc19314da1db89b9530e4bece09caa1cefa81b06da08723a5ea2de68" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:6bf86f3bfc19314da1db89b9530e4bece09caa1cefa81b06da08723a5ea2de68
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:04cf1b47c5a0895b1cf295060efe04286370074a94f6971e5a8bdcd46f41fcd1" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:04cf1b47c5a0895b1cf295060efe04286370074a94f6971e5a8bdcd46f41fcd1" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:04cf1b47c5a0895b1cf295060efe04286370074a94f6971e5a8bdcd46f41fcd1
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:1e5acd71f269e9ceb7067c5725ca952a8e9d0a391501443abdb0c420e7fd90bb" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:1e5acd71f269e9ceb7067c5725ca952a8e9d0a391501443abdb0c420e7fd90bb" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:1e5acd71f269e9ceb7067c5725ca952a8e9d0a391501443abdb0c420e7fd90bb
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:b1a67efc903ff1fe346457de4a6f05450ceee734d86a139b55dd4c7ee0c8bbfe" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:b1a67efc903ff1fe346457de4a6f05450ceee734d86a139b55dd4c7ee0c8bbfe" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:b1a67efc903ff1fe346457de4a6f05450ceee734d86a139b55dd4c7ee0c8bbfe
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:78a76af193ea1ba85efe949c623d039cd8826eb490601da6bc576d749f08d323" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:78a76af193ea1ba85efe949c623d039cd8826eb490601da6bc576d749f08d323" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:78a76af193ea1ba85efe949c623d039cd8826eb490601da6bc576d749f08d323
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:8ccced0f514a9ba05360dddc9fb5cfdd89e78f6d5ba3a0a9b7aa6a59c43ee0ec" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:8ccced0f514a9ba05360dddc9fb5cfdd89e78f6d5ba3a0a9b7aa6a59c43ee0ec" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:8ccced0f514a9ba05360dddc9fb5cfdd89e78f6d5ba3a0a9b7aa6a59c43ee0ec
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:a21ad575749b51a87b4eccdc7a04a8a0084f7bf163d33902f5f7fdabdf87b3b3" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:a21ad575749b51a87b4eccdc7a04a8a0084f7bf163d33902f5f7fdabdf87b3b3" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:a21ad575749b51a87b4eccdc7a04a8a0084f7bf163d33902f5f7fdabdf87b3b3
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:9288470e38de40b25b12e0df23188a3f7c5056d88523d388dd3c68c574b9ba53" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:9288470e38de40b25b12e0df23188a3f7c5056d88523d388dd3c68c574b9ba53" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:9288470e38de40b25b12e0df23188a3f7c5056d88523d388dd3c68c574b9ba53
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:683ba06a68e23037b9d7f8ccb0b3c549aeeaacbc89b95402907cf494dd4a30cf" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:683ba06a68e23037b9d7f8ccb0b3c549aeeaacbc89b95402907cf494dd4a30cf" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:683ba06a68e23037b9d7f8ccb0b3c549aeeaacbc89b95402907cf494dd4a30cf
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:065359ed5ca2e7fda126d07cf4cd9f574462b982838a509385dbae0a38a2d132" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:065359ed5ca2e7fda126d07cf4cd9f574462b982838a509385dbae0a38a2d132" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:065359ed5ca2e7fda126d07cf4cd9f574462b982838a509385dbae0a38a2d132
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:500f7dff4dd0433ad4b16023d89045f39352e5be4c27153cc6b691e22c0f3351" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:500f7dff4dd0433ad4b16023d89045f39352e5be4c27153cc6b691e22c0f3351" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:500f7dff4dd0433ad4b16023d89045f39352e5be4c27153cc6b691e22c0f3351
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:d1b259a4ee48604ec87cc764935d6f9df44816ec53a4d6c15151cadded323686" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:d1b259a4ee48604ec87cc764935d6f9df44816ec53a4d6c15151cadded323686" 
time="2017-08-28T14:33:12+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:d1b259a4ee48604ec87cc764935d6f9df44816ec53a4d6c15151cadded323686
time="2017-08-28T14:33:12+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2017-08-28T14:33:12+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2017-08-28T14:33:13+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
time="2017-08-28T14:33:13+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2017-08-28T14:33:13+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2017-08-28T14:33:13+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
time="2017-08-28T14:33:13+02:00" level=debug msg="Checking myorg/myrepoe/blobs/sha256:56f97170027f7e2a5631e45fcc00559c2af5456ebfaa917427fd5ecdd36bafcb" 
time="2017-08-28T14:33:13+02:00" level=debug msg="HEAD https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/blobs/sha256:56f97170027f7e2a5631e45fcc00559c2af5456ebfaa917427fd5ecdd36bafcb" 
time="2017-08-28T14:33:13+02:00" level=debug msg="... already exists" 
Skipping fetch of repeat blob sha256:56f97170027f7e2a5631e45fcc00559c2af5456ebfaa917427fd5ecdd36bafcb
Writing manifest to image destination
time="2017-08-28T14:33:13+02:00" level=debug msg="PUT https://docker-registry-default.cloudapps.mycompany.com/v2/myorg/myrepoe/manifests/prod" 
time="2017-08-28T14:33:13+02:00" level=debug msg="Error body {\"errors\":[{\"code\":\"UNKNOWN\",\"message\":\"unknown error\",\"detail\":{\"ErrStatus\":{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"imagestreams \\\"myrepoe\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"myrepoe\",\"kind\":\"imagestreams\"},\"code\":404}}}]}\n" 
time="2017-08-28T14:33:13+02:00" level=debug msg="Error uploading manifest, status 500, &http.Response{Status:\"500 Internal Server Error\", StatusCode:500, Proto:\"HTTP/1.1\", ProtoMajor:1, ProtoMinor:1, Header:http.Header{\"Content-Type\":[]string{\"application/json; charset=utf-8\"}, \"Docker-Distribution-Api-Version\":[]string{\"registry/2.0\"}, \"Date\":[]string{\"Mon, 28 Aug 2017 12:33:13 GMT\"}, \"Content-Length\":[]string{\"309\"}}, Body:(*http.bodyEOFSignal)(0xc4201d5700), ContentLength:309, TransferEncoding:[]string(nil), Close:true, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc420276e10), TLS:(*tls.ConnectionState)(0xc420223760)}" 
time="2017-08-28T14:33:13+02:00" level=fatal msg="Error writing manifest: Error uploading manifest to myorg/myrepoe/manifests/prod, status 500" 
```

**Comment by runcom** [comment] 2017-08-28 12:48
so this is an openshift issue, please report your findings over there. Might make sense to behave like the docker hub indeed.

**Comment by mtrmac** [comment] 2017-08-28 16:01
```
time="2017-08-28T14:33:13+02:00" level=debug msg="Error body {\"errors\":[{\"code\":\"UNKNOWN\",\"message\":\"unknown error\",\"detail\":{\"ErrStatus\":{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"imagestreams \\\"myrepoe\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"myrepoe\",\"kind\":\"imagestreams\"},\"code\":404}}}]}\n" 
```

Still, containers/image is throwing away this useful information. We should be able to parse this and report the “image stream not found” message to the users.

**Comment by runcom** [comment] 2017-08-28 16:22
Yeah

**Comment by fntlnz** [comment] 2017-08-28 16:56
@mtrmac that information is  hidden by `containers/image`'s [PutManifest](https://github.com/containers/image/blob/74e359348c7ce9e0caf4fa75aa8de3809cf41c46/docker/docker_image_dest.go#L248-L251) while formatting the error 
https://github.com/projectatomic/skopeo/blob/0224d8cd387b69f1d48d7727e303e4e95a02c2af/cmd/skopeo/layers.go#L114


Should we open an issue there?

**Comment by fntlnz** [comment] 2017-08-28 17:00
Also @runcom it's not the server that is handling the upload differently but the client, in fact skopeo, here
https://github.com/projectatomic/skopeo/blob/0224d8cd387b69f1d48d7727e303e4e95a02c2af/cmd/skopeo/layers.go#L97-L106
is uploading all the blobs and then the manifest. 

I don't know if those two things can be swapped by doing `PutManifest` before than `PutBlob` or if there's any technical limitation in doing that

**Comment by runcom** [comment] 2017-08-28 17:03
PutManifest must always come last, it's the registry API

**Comment by fntlnz** [comment] 2017-08-28 17:08
Ok so would be an option to check if the manifest can-be-put before than writing?

**Comment by fntlnz** [comment] 2017-08-28 17:09
Anyway the best place to discuss about this is that repo atm

**Comment by mtrmac** [comment] 2017-08-28 17:20
> Ok so would be an option to check if the manifest can-be-put before than writing?

Nothing of that kind exists, AFAICT.

Given the design of the registry API, the only way to prevent the user from uploading all the layers and only later noticing that the repo is inaccessible for writing is for the _server_ to reject already the initial blob uploads (the blob uploads also include the repo name).

**Comment by fntlnz** [comment] 2017-08-28 18:35
In the actual `docker/cli` this is implemented by doing a preventive `POST` on the resource and if that returns `202 Accepted` the layers are pushed.

Also, given that 202, the semantic is pretty clear.

Maybe here we can do the same?

**Comment by mtrmac** [comment] 2017-08-28 18:50
> In the actual `docker/cli` this is implemented by doing a preventive `POST` on the resource

Could you elaborate, please? What resource, what request?

AFAICS from https://github.com/moby/moby/blob/master/distribution/push_v2.go#L170 , `docker/cli` also finishes upload of all the blobs before dealing with manifests at all.

Or do you mean the `POST /v2/…/blobs/uploads/`? Sure, that’s a mandatory part of the blob upload process, and containers/image does that as well, but the point is that the remote repo must actually reject the upload attempt at that time instead of accepting it and only checking permissions at manifest upload time.

(Well, strictly speaking, this is kind of theoretical, because all the attached logs show that the client has detected that the blobs already exists, so it does not attempt to upload any of them; so, the server has _no opportunity_ to say ”you don’t have write access to this repo” before we start to upload the manifest. I’m assuming that you saw the upload be actually performed, and succeed, sometime in the past.  Or maybe that’s not the case and we are only talking about the ”skipping fetch of repeat blob” process?)

**Comment by fntlnz** [comment] 2017-09-04 07:39
@mtrmac sorry for being unclear.

If I understand the flow correctly, in the `docker/cli` things are happening in this order:

- The users initiate the upload via the 'docker image push <something>` command
- After some magic, layer are being pushed in a loop
- While pushing the [`blobs.Create`](https://github.com/docker/cli/blob/master/vendor/github.com/docker/distribution/registry/client/repository.go#L704) is called twice for each layer, [here](https://github.com/moby/moby/blob/9b4a616e4b3819ef062780b5fd854616be2c22bb/distribution/push_v2.go#L336) and [here](https://github.com/moby/moby/blob/master/distribution/push_v2.go#L390) - the first call is supposed to do the actual creation but if [it doesn't and does not trigger errors](https://github.com/docker/cli/blob/master/vendor/github.com/docker/distribution/registry/client/repository.go#L738) then it does not fill  the [`layerUpload`](https://github.com/moby/moby/blob/master/distribution/push_v2.go#L389) variable causing a retry. After all that happening the blob is actually [uploaded](https://github.com/moby/moby/blob/master/distribution/push_v2.go#L398)

So AFAICS the current upload rejection is implemented client side which is not ideal but at least this is managed in some way.

I think we have two different options here:
- Reproduce client side rejection in `containers/image`
- Report this behavior to the current registry implementations we use so that it can be handled also at that level

In any case the user needs to be warned about the fact that she/he doesn't have access to the repo or that it doesn't exists.

This can sound stupid but I've seen various situations where I personally or others I work with we have lost time figuring out this. Also in setups where one has Origin (for example) but he is not the cluster admin can be very difficult to debug the problem.

**Comment by runcom** [comment] 2017-09-04 07:47
Pretty sure by client, you mean the Docker daemon and not the docker/cli, the cli just calls the daemon which in turns calls the registry. We're interested in what happens in the daemon here.
BTW I'll take a look at this shortly.

**Comment by fntlnz** [comment] 2017-09-04 07:48
@runcom yeah sorry, I mixed the terminology but that's what I meant

**Comment by runcom** [comment] 2017-09-04 07:50
@fntlnz you said this was working with Docker in your first comment, how so if the image stream doesn't exist? Can you reproduce this situation with Docker? Afaict this shouldn't work with Docker either...

**Comment by runcom** [comment] 2017-09-04 08:31
@fntlnz Please provide skopeo version also

**Comment by runcom** [comment] 2017-09-04 08:37
There's so confusion in this issue though, skopeo doesn't push layers if it's not authorized to the destination repo...:
```
10:35:39 [github.com/openshift/origin] ‹master› skopeo copy docker://busybox docker://docker.io/fntlnz/cantpushere         1 ↵
Getting image source signatures
FATA[0006] Error checking for blob sha256:add3ddb21edebb102b552fc129273216bf6312f5f1519d7c1401864a2810738b at destination: not authorized to read from destination repository fntlnz/cantpushere
```
The only thing to fix here is IMO bubbling up the error from Origin

**Comment by runcom** [comment] 2017-09-04 09:15
Blobs stuff seems to be working correctly indeed:
```
11:14:24 [github.com/docker/docker] ‹docker-1.13.1-rhel› skopeo copy --dest-tls-verify=false docker://busybox docker://172.30.1.1:5000/myorg/myrepo:prod
Getting image source signatures
FATA[0002] Error checking for blob sha256:add3ddb21edebb102b552fc129273216bf6312f5f1519d7c1401864a2810738b at destination: not authorized to read from destination repository myorg/myrepo
```

**Comment by runcom** [comment] 2017-09-04 09:26
I cannot reproduce this btw:
```
$ skopeo copy --dest-tls-verify=false docker://busybox docker://172.30.1.1:5000/myproject/myrepo:prod
[WORKS JUST FINE]
```
Please provide skopeo version and a _correct_ reproducer.

**Comment by mtrmac** [comment] 2017-09-04 16:58
The description in https://github.com/projectatomic/skopeo/issues/402#issuecomment-326888468 describes in detail in how _blobs_ get uploaded, but AFAICT not a “preventive POST on the resource and if that returns 202 Accepted the layers are pushed.” to determine whether “the manifest can-be-put before than writing”.

---

Potentially confusing is that these log entries
```
Skipping fetch of repeat blob sha256:b25889d273102779a1d372b4e6590da9916fe594300bf1573cb9a6521a57c25e
```

1. Do _not_ actually require write permission; we can detect that a blob re-upload is not necessary without any write permissions; i.e. no failure can happen for the ”Skipping fetch” operations if the remote repo is not writable; the manifest upload is really the first operation that can fail in this particular case.
2. _Only_ happen if the blobs are already present at the destination, which is not generally the case; usually uploading a new image means uploading at least one blob.

---

> The only thing to fix here is IMO bubbling up the error from Origin (/cc @mtrmac ...).

Seems so; well, that and the ”Skipping fetch of repeat blob“ log lines should probably be improved to say something like ”Blob $digest already exists at the destination”.

**Comment by rhatdan** [comment] 2019-04-25 12:05
I think we have much better pulling/pushing semantics, Closing, reopen if this is still an issue.

**Closed by rhatdan** 2019-04-25 12:05 UTC
